// ─── REAL FC 26 PLAYER DATABASE (verified ratings, June 2026) ───────────────
exports.GLOBAL_POOL = [
  {
    name: "Gregor Kobel",
    pos: "POR",
    nat: "Switzerland",
    club: "Dortmund",
    overall: 86,
    pace: 46,
    shooting: 16,
    passing: 72,
    dribbling: 40,
    defending: 13,
    physical: 78,
  },
  {
    name: "Joan García",
    pos: "POR",
    nat: "Spain",
    club: "Barcelona",
    overall: 86,
    pace: 52,
    shooting: 18,
    passing: 74,
    dribbling: 44,
    defending: 14,
    physical: 72,
  },
  {
    name: "Yann Sommer",
    pos: "POR",
    nat: "Switzerland",
    club: "Inter Milan",
    overall: 86,
    pace: 48,
    shooting: 18,
    passing: 72,
    dribbling: 42,
    defending: 13,
    physical: 76,
  },
  {
    name: "Mohamed Salah",
    pos: "ED",
    nat: "Egypt",
    club: "Liverpool",
    overall: 89,
    pace: 91,
    shooting: 89,
    passing: 81,
    dribbling: 89,
    defending: 45,
    physical: 75,
  },
  {
    name: "Kylian Mbappé",
    pos: "DC",
    nat: "France",
    club: "Real Madrid",
    overall: 91,
    pace: 97,
    shooting: 90,
    passing: 80,
    dribbling: 92,
    defending: 36,
    physical: 78,
  },
  {
    name: "Ousmane Dembélé",
    pos: "ED",
    nat: "France",
    club: "PSG",
    overall: 90,
    pace: 90,
    shooting: 85,
    passing: 82,
    dribbling: 93,
    defending: 30,
    physical: 74,
  },
  {
    name: "Jan Oblak",
    pos: "POR",
    nat: "Slovenia",
    club: "Atletico de Madrid",
    overall: 88,
    pace: 90,
    shooting: 85,
    passing: 82,
    dribbling: 93,
    defending: 30,
    physical: 74,
  },
  {
    name: "Rodri",
    pos: "MCD",
    nat: "Spain",
    club: "Manchester City",
    overall: 89,
    pace: 63,
    shooting: 74,
    passing: 88,
    dribbling: 84,
    defending: 89,
    physical: 84,
  },
  {
    name: "Virgil van Dijk",
    pos: "DFC",
    nat: "Netherlands",
    club: "Liverpool",
    overall: 88,
    pace: 78,
    shooting: 60,
    passing: 78,
    dribbling: 72,
    defending: 91,
    physical: 88,
  },
  {
    name: "Kevin de Bruyne",
    pos: "MC",
    nat: "Belgium",
    club: "Napoli",
    overall: 87,
    pace: 78,
    shooting: 60,
    passing: 78,
    dribbling: 72,
    defending: 91,
    physical: 88,
  },
  {
    name: "Jude Bellingham",
    pos: "MCO",
    nat: "England",
    club: "Real Madrid",
    overall: 89,
    pace: 80,
    shooting: 87,
    passing: 83,
    dribbling: 88,
    defending: 78,
    physical: 83,
  },
  {
    name: "Thibaut Courtois",
    pos: "POR",
    nat: "Belgium",
    club: "Real Madrid",
    overall: 90,
    pace: 80,
    shooting: 87,
    passing: 83,
    dribbling: 88,
    defending: 78,
    physical: 83,
  },
  {
    name: "Erling Haaland",
    pos: "DC",
    nat: "Norway",
    club: "Manchester City",
    overall: 91,
    pace: 88,
    shooting: 93,
    passing: 66,
    dribbling: 81,
    defending: 29,
    physical: 89,
  },
  {
    name: "Raphinha",
    pos: "EI",
    nat: "Brazil",
    club: "Barcelona",
    overall: 89,
    pace: 90,
    shooting: 84,
    passing: 83,
    dribbling: 88,
    defending: 42,
    physical: 70,
  },
  {
    name: "Lamine Yamal",
    pos: "ED",
    nat: "Spain",
    club: "Barcelona",
    overall: 89,
    pace: 88,
    shooting: 82,
    passing: 85,
    dribbling: 91,
    defending: 32,
    physical: 62,
  },
  {
    name: "Achraf Hakimi",
    pos: "LD",
    nat: "Morocco",
    club: "PSG",
    overall: 89,
    pace: 92,
    shooting: 75,
    passing: 80,
    dribbling: 85,
    defending: 79,
    physical: 77,
  },
  {
    name: "Vitinha",
    pos: "MC",
    nat: "Portugal",
    club: "PSG",
    overall: 90,
    pace: 78,
    shooting: 78,
    passing: 88,
    dribbling: 90,
    defending: 74,
    physical: 70,
  },
  {
    name: "Nicolò Barella",
    pos: "MC",
    nat: "Italy",
    club: "Inter Milan",
    overall: 88,
    pace: 78,
    shooting: 78,
    passing: 84,
    dribbling: 85,
    defending: 78,
    physical: 80,
  },
  {
    name: "Gianluigi Donnarumma",
    pos: "POR",
    nat: "Italy",
    club: "Manchester City",
    overall: 89,
    pace: 50,
    shooting: 20,
    passing: 75,
    dribbling: 42,
    defending: 14,
    physical: 82,
  },
  {
    name: "Joshua Kimmich",
    pos: "MCD",
    nat: "Germany",
    club: "Bayern Munich",
    overall: 89,
    pace: 70,
    shooting: 77,
    passing: 89,
    dribbling: 84,
    defending: 86,
    physical: 75,
  },
  {
    name: "Alisson",
    pos: "POR",
    nat: "Brazil",
    club: "Liverpool",
    overall: 88,
    pace: 48,
    shooting: 20,
    passing: 79,
    dribbling: 43,
    defending: 15,
    physical: 66,
  },
  {
    name: "Harry Kane",
    pos: "DC",
    nat: "England",
    club: "Bayern Munich",
    overall: 90,
    pace: 71,
    shooting: 91,
    passing: 84,
    dribbling: 84,
    defending: 46,
    physical: 84,
  },
  {
    name: "Fede Valverde",
    pos: "MC",
    nat: "Uruguay",
    club: "Real Madrid",
    overall: 89,
    pace: 88,
    shooting: 84,
    passing: 84,
    dribbling: 85,
    defending: 79,
    physical: 86,
  },
  {
    name: "Vinícius Júnior",
    pos: "EI",
    nat: "Brazil",
    club: "Real Madrid",
    overall: 89,
    pace: 95,
    shooting: 84,
    passing: 81,
    dribbling: 91,
    defending: 29,
    physical: 69,
  },
  {
    name: "Florian Wirtz",
    pos: "MCO",
    nat: "Germany",
    club: "Liverpool",
    overall: 87,
    pace: 81,
    shooting: 81,
    passing: 87,
    dribbling: 90,
    defending: 51,
    physical: 69,
  },
  {
    name: "Bukayo Saka",
    pos: "ED",
    nat: "England",
    club: "Arsenal",
    overall: 87,
    pace: 87,
    shooting: 84,
    passing: 83,
    dribbling: 87,
    defending: 48,
    physical: 73,
  },
  {
    name: "Gabriel Magalhães",
    pos: "DFC",
    nat: "Brazil",
    club: "Arsenal",
    overall: 89,
    pace: 75,
    shooting: 55,
    passing: 68,
    dribbling: 62,
    defending: 88,
    physical: 87,
  },
  {
    name: "Alexander Isak",
    pos: "DC",
    nat: "Sweden",
    club: "Liverpool",
    overall: 87,
    pace: 88,
    shooting: 87,
    passing: 74,
    dribbling: 85,
    defending: 32,
    physical: 78,
  },
  {
    name: "Jamal Musiala",
    pos: "MCO",
    nat: "Germany",
    club: "Bayern Munich",
    overall: 87,
    pace: 80,
    shooting: 82,
    passing: 80,
    dribbling: 90,
    defending: 66,
    physical: 65,
  },
  {
    name: "Michael Olise",
    pos: "ED",
    nat: "France",
    club: "Bayern Munich",
    overall: 89,
    pace: 87,
    shooting: 82,
    passing: 83,
    dribbling: 89,
    defending: 35,
    physical: 68,
  },
  {
    name: "João Neves",
    pos: "MC",
    nat: "Portugal",
    club: "PSG",
    overall: 88,
    pace: 78,
    shooting: 74,
    passing: 83,
    dribbling: 86,
    defending: 80,
    physical: 73,
  },
  {
    name: "Nuno Mendes",
    pos: "LI",
    nat: "Portugal",
    club: "PSG",
    overall: 88,
    pace: 90,
    shooting: 65,
    passing: 78,
    dribbling: 84,
    defending: 82,
    physical: 75,
  },
  {
    name: "Bruno Fernandes",
    pos: "MCO",
    nat: "Portugal",
    club: "Manchester United",
    overall: 88,
    pace: 73,
    shooting: 84,
    passing: 88,
    dribbling: 85,
    defending: 65,
    physical: 74,
  },
  {
    name: "Declan Rice",
    pos: "MCD",
    nat: "England",
    club: "Arsenal",
    overall: 88,
    pace: 76,
    shooting: 72,
    passing: 81,
    dribbling: 81,
    defending: 85,
    physical: 84,
  },
  {
    name: "Lautaro Martínez",
    pos: "DC",
    nat: "Argentina",
    club: "Inter",
    overall: 88,
    pace: 84,
    shooting: 88,
    passing: 80,
    dribbling: 85,
    defending: 60,
    physical: 64,
  },
  {
    name: "Willian Pacho",
    pos: "DFC",
    nat: "Ecuador",
    club: "PSG",
    overall: 88,
    pace: 80,
    shooting: 70,
    passing: 81,
    dribbling: 82,
    defending: 86,
    physical: 81,
  },
  {
    name: "Moisés Caicedo",
    pos: "MCD",
    nat: "Ecuador",
    club: "Chelsea",
    overall: 88,
    pace: 80,
    shooting: 70,
    passing: 81,
    dribbling: 82,
    defending: 86,
    physical: 81,
  },
  {
    name: "William Saliba",
    pos: "DFC",
    nat: "France",
    club: "Arsenal",
    overall: 88,
    pace: 82,
    shooting: 48,
    passing: 70,
    dribbling: 62,
    defending: 87,
    physical: 84,
  },
  {
    name: "Alessandro Bastoni",
    pos: "DFC",
    nat: "Italy",
    club: "Inter Milan",
    overall: 87,
    pace: 74,
    shooting: 48,
    passing: 80,
    dribbling: 70,
    defending: 86,
    physical: 80,
  },
  {
    name: "Rúben Dias",
    pos: "DFC",
    nat: "Portugal",
    club: "Manchester City",
    overall: 87,
    pace: 73,
    shooting: 45,
    passing: 74,
    dribbling: 60,
    defending: 90,
    physical: 86,
  },
  {
    name: "Khvicha Kvaratskhelia",
    pos: "EI",
    nat: "Georgia",
    club: "PSG",
    overall: 88,
    pace: 86,
    shooting: 84,
    passing: 85,
    dribbling: 89,
    defending: 68,
    physical: 70,
  },
  {
    name: "Alexis Mac Allister",
    pos: "MC",
    nat: "Argentina",
    club: "Liverpool",
    overall: 85,
    pace: 72,
    shooting: 78,
    passing: 85,
    dribbling: 86,
    defending: 68,
    physical: 70,
  },
  {
    name: "David Raya",
    pos: "POR",
    nat: "Spain",
    club: "Arsenal",
    overall: 87,
    pace: 50,
    shooting: 18,
    passing: 80,
    dribbling: 46,
    defending: 14,
    physical: 70,
  },
  {
    name: "Serhou Guirassy",
    pos: "DC",
    nat: "Guinea",
    club: "Dortmund",
    overall: 85,
    pace: 80,
    shooting: 86,
    passing: 64,
    dribbling: 78,
    defending: 30,
    physical: 82,
  },
  {
    name: "Marquinhos",
    pos: "DFC",
    nat: "Brazil",
    club: "PSG",
    overall: 87,
    pace: 72,
    shooting: 50,
    passing: 76,
    dribbling: 68,
    defending: 88,
    physical: 80,
  },
  {
    name: "Jonathan Tah",
    pos: "DFC",
    nat: "Germany",
    club: "Bayern Munich",
    overall: 87,
    pace: 74,
    shooting: 42,
    passing: 70,
    dribbling: 64,
    defending: 88,
    physical: 87,
  },
  {
    name: "Trent Alexander-Arnold",
    pos: "LD",
    nat: "England",
    club: "Real Madrid",
    overall: 85,
    pace: 76,
    shooting: 74,
    passing: 90,
    dribbling: 82,
    defending: 72,
    physical: 68,
  },
  {
    name: "Luis Díaz",
    pos: "EI",
    nat: "Colombia",
    club: "Bayern Munich",
    overall: 87,
    pace: 90,
    shooting: 80,
    passing: 75,
    dribbling: 87,
    defending: 38,
    physical: 72,
  },
  {
    name: "Patrik Schick",
    pos: "DC",
    nat: "Czech Republic",
    club: "Bayer Leverkusen",
    overall: 85,
    pace: 78,
    shooting: 84,
    passing: 70,
    dribbling: 79,
    defending: 30,
    physical: 84,
  },
  {
    name: "Ibrahima Konaté",
    pos: "DFC",
    nat: "France",
    club: "Liverpool",
    overall: 84,
    pace: 84,
    shooting: 42,
    passing: 65,
    dribbling: 58,
    defending: 87,
    physical: 88,
  },
  {
    name: "Lukaku",
    pos: "DC",
    nat: "Belgium",
    club: "Napoli",
    overall: 83,
    pace: 84,
    shooting: 86,
    passing: 82,
    dribbling: 88,
    defending: 47,
    physical: 86,
  },
  {
    name: "Theo Hernández",
    pos: "LI",
    nat: "France",
    club: "Al-Hilal",
    overall: 84,
    pace: 90,
    shooting: 72,
    passing: 74,
    dribbling: 80,
    defending: 78,
    physical: 80,
  },
  {
    name: "Péter Gulácsi",
    pos: "POR",
    nat: "Hungary",
    club: "RB Leipzig",
    overall: 84,
    pace: 42,
    shooting: 15,
    passing: 70,
    dribbling: 38,
    defending: 12,
    physical: 68,
  },
  {
    name: "Bryan Mbeumo",
    pos: "DC",
    nat: "Cameroon",
    club: "Manchester United",
    overall: 85,
    pace: 84,
    shooting: 84,
    passing: 76,
    dribbling: 83,
    defending: 38,
    physical: 74,
  },
  {
    name: "Unai Simón",
    pos: "POR",
    nat: "Spain",
    club: "Athletic Club",
    overall: 84,
    pace: 42,
    shooting: 14,
    passing: 72,
    dribbling: 40,
    defending: 11,
    physical: 74,
  },
  {
    name: "Diogo Costa",
    pos: "POR",
    nat: "Portugal",
    club: "Porto",
    overall: 84,
    pace: 44,
    shooting: 14,
    passing: 70,
    dribbling: 38,
    defending: 11,
    physical: 72,
  },
  {
    name: "Jordan Pickford",
    pos: "POR",
    nat: "England",
    club: "Everton",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Emiliano Martínez",
    pos: "POR",
    nat: "Argentina",
    club: "Aston Villa",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Karim Benzema",
    pos: "DC",
    nat: "France",
    club: "Al Hilal",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Cristiano Ronaldo",
    pos: "DC",
    nat: "Portugal",
    club: "Al Nassr",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Bradley Barcola",
    pos: "EI",
    nat: "France",
    club: "PSG",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Morgan Rogers",
    pos: "MCO",
    nat: "England",
    club: "Aston Villa",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Rayan Cherki",
    pos: "ED",
    nat: "France",
    club: "Manchester City",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Rodrygo",
    pos: "ED",
    nat: "Brazil",
    club: "Real Madrid",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Antoine Semenyo",
    pos: "ED",
    nat: "Ghana",
    club: "Manchester City",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Eder Militao",
    pos: "DFC",
    nat: "Brazil",
    club: "Real Madrid",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Eberechi Eze",
    pos: "MCO",
    nat: "England",
    club: "Arsenal",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Denzel Dumfries",
    pos: "LD",
    nat: "Netherlands",
    club: "Inter Milan",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Ngolo Kanté",
    pos: "MCD",
    nat: "France",
    club: "Fenerbahçe",
    overall: 84,
    pace: 62,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Joao Cancelo",
    pos: "LD",
    nat: "Portugal",
    club: "Barcelona",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Antonio Rudiger",
    pos: "DFC",
    nat: "Germany",
    club: "Real Madrid",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Dani Carvajal",
    pos: "LD",
    nat: "Spain",
    club: "Real Madrid",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Son Heung-min",
    pos: "EI",
    nat: "South Korea",
    club: "LA FC",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Riyad Mahrez",
    pos: "ED",
    nat: "Algeria",
    club: "Al Ahli",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Isco",
    pos: "MCO",
    nat: "Spain",
    club: "Real Betis",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Antoine Griezmann",
    pos: "DC",
    nat: "France",
    club: "Atletico de Madrid",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "David de Gea",
    pos: "POR",
    nat: "Spain",
    club: "Fiorentina",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Marc André ter Stegen",
    pos: "POR",
    nat: "Germany",
    club: "Girona",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Pau Cubarsí",
    pos: "DFC",
    nat: "Spain",
    club: "Barcelona",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Arda Güler",
    pos: "MCO",
    nat: "Turkey",
    club: "Real Madrid",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Warren Zaïre-Emery",
    pos: "MC",
    nat: "France",
    club: "PSG",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Gavi",
    pos: "MC",
    nat: "Spain",
    club: "Barcelona",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Alejandro Balde",
    pos: "LI",
    nat: "Spain",
    club: "Barcelona",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Omar Marmoush",
    pos: "DC",
    nat: "Egypt",
    club: "Manchester City",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Piero Hincapié",
    pos: "LI",
    nat: "Ecuador",
    club: "Arsenal",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Giorgi Mamardashvili",
    pos: "POR",
    nat: "Georgia",
    club: "Liverpool",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Jeremy Doku",
    pos: "EI",
    nat: "Belgium",
    club: "Manchester City",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Mason Greenwood",
    pos: "ED",
    nat: "England",
    club: "Olympique Marseille",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Moussa Diaby",
    pos: "ED",
    nat: "France",
    club: "Al Ittihad",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Cody Gakpo",
    pos: "EI",
    nat: "Netherlands",
    club: "Liverpool",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "David Raum",
    pos: "LI",
    nat: "Germany",
    club: "RB Leipzig",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Ademola Lookman",
    pos: "EI",
    nat: "Nigeria",
    club: "Atletico de Madrid",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Manuel Akanji",
    pos: "DFC",
    nat: "Switzerland",
    club: "Inter Milan",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "André-Franck Zambo Anguissa",
    pos: "MC",
    nat: "Cameroon",
    club: "Napoli",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Bernardo Silva",
    pos: "MC",
    nat: "Portugal",
    club: "Manchester City",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Giovanni Di Lorenzo",
    pos: "LD",
    nat: "Italy",
    club: "Napoli",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Sadio Mané",
    pos: "EI",
    nat: "Senegal",
    club: "Al Nassr",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Neymar Jr.",
    pos: "MCO",
    nat: "Brazil",
    club: "Free Agent",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Fermín",
    pos: "MCO",
    nat: "Spain",
    club: "Barcelona",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Mike Maignan",
    pos: "POR",
    nat: "France",
    club: "AC Milan",
    overall: 87,
    pace: 52,
    shooting: 18,
    passing: 78,
    dribbling: 46,
    defending: 14,
    physical: 80,
  },
  {
    name: "Rafael Leão",
    pos: "DC",
    nat: "Portugal",
    club: "AC Milan",
    overall: 84,
    pace: 93,
    shooting: 80,
    passing: 75,
    dribbling: 88,
    defending: 30,
    physical: 78,
  },
  {
    name: "Luka Modrić",
    pos: "MCD",
    nat: "Croatia",
    club: "AC Milan",
    overall: 85,
    pace: 62,
    shooting: 76,
    passing: 89,
    dribbling: 87,
    defending: 60,
    physical: 60,
  },
  {
    name: "Matheus Cunha",
    pos: "EI",
    nat: "Brazil",
    club: "Manchester United",
    overall: 83,
    pace: 82,
    shooting: 80,
    passing: 76,
    dribbling: 84,
    defending: 40,
    physical: 78,
  },
  {
    name: "Adrien Rabiot",
    pos: "MC",
    nat: "France",
    club: "AC Milan",
    overall: 85,
    pace: 72,
    shooting: 78,
    passing: 82,
    dribbling: 80,
    defending: 74,
    physical: 84,
  },
  {
    name: "Granit Xhaka",
    pos: "MCD",
    nat: "Switzerland",
    club: "Sunderland",
    overall: 85,
    pace: 62,
    shooting: 74,
    passing: 84,
    dribbling: 78,
    defending: 82,
    physical: 78,
  },
  {
    name: "James Maddison",
    pos: "MCO",
    nat: "England",
    club: "Tottenham",
    overall: 83,
    pace: 70,
    shooting: 80,
    passing: 86,
    dribbling: 88,
    defending: 42,
    physical: 62,
  },
  {
    name: "Pedri",
    pos: "MC",
    nat: "Spain",
    club: "Barcelona",
    overall: 90,
    pace: 75,
    shooting: 78,
    passing: 88,
    dribbling: 90,
    defending: 78,
    physical: 65,
  },
  {
    name: "Martín Zubimendi",
    pos: "MCD",
    nat: "Spain",
    club: "Arsenal",
    overall: 85,
    pace: 68,
    shooting: 72,
    passing: 85,
    dribbling: 82,
    defending: 84,
    physical: 72,
  },
  {
    name: "Enzo Fernández",
    pos: "MC",
    nat: "Argentina",
    club: "Chelsea",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Sandro Tonali",
    pos: "MCD",
    nat: "Italy",
    club: "Newcastle United",
    overall: 85,
    pace: 68,
    shooting: 75,
    passing: 84,
    dribbling: 82,
    defending: 80,
    physical: 78,
  },
  {
    name: "Tijjani Reijnders",
    pos: "MC",
    nat: "Netherlands",
    club: "Manchester City",
    overall: 85,
    pace: 79,
    shooting: 78,
    passing: 84,
    dribbling: 86,
    defending: 68,
    physical: 70,
  },
  {
    name: "Fabián Ruiz",
    pos: "MC",
    nat: "Spain",
    club: "PSG",
    overall: 85,
    pace: 68,
    shooting: 80,
    passing: 86,
    dribbling: 85,
    defending: 70,
    physical: 70,
  },
  {
    name: "Marcos Llorente",
    pos: "LD",
    nat: "Spain",
    club: "Atletico de Madrid",
    overall: 85,
    pace: 90,
    shooting: 78,
    passing: 78,
    dribbling: 82,
    defending: 75,
    physical: 82,
  },
  {
    name: "Nico Williams",
    pos: "EI",
    nat: "Spain",
    club: "Athletic Club",
    overall: 85,
    pace: 93,
    shooting: 78,
    passing: 78,
    dribbling: 88,
    defending: 30,
    physical: 65,
  },
  {
    name: "Dani Olmo",
    pos: "MCO",
    nat: "Spain",
    club: "Barcelona",
    overall: 84,
    pace: 78,
    shooting: 80,
    passing: 84,
    dribbling: 87,
    defending: 50,
    physical: 65,
  },
  {
    name: "Ferran Torres",
    pos: "DC",
    nat: "Spain",
    club: "Barcelona",
    overall: 84,
    pace: 84,
    shooting: 82,
    passing: 76,
    dribbling: 84,
    defending: 35,
    physical: 68,
  },
  {
    name: "Marc Cucurella",
    pos: "LI",
    nat: "Spain",
    club: "Chelsea",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Phil Foden",
    pos: "MCO",
    nat: "England",
    club: "Manchester City",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Marcus Thuram",
    pos: "DC",
    nat: "France",
    club: "Inter Milan",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Christian Pulisic",
    pos: "ED",
    nat: "United States",
    club: "AC Milan",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Ruben Neves",
    pos: "MCD",
    nat: "Portugal",
    club: "Al Hilal",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Sergej Milinković-Savić",
    pos: "MC",
    nat: "Serbia",
    club: "Al Hilal",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Youri Tielemans",
    pos: "MC",
    nat: "Belgium",
    club: "Aston Villa",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Gavi",
    pos: "MC",
    nat: "Spain",
    club: "Barcelona",
    overall: 83,
    pace: 78,
    shooting: 72,
    passing: 80,
    dribbling: 84,
    defending: 72,
    physical: 70,
  },
  {
    name: "Mikel Merino",
    pos: "MC",
    nat: "Spain",
    club: "Arsenal",
    overall: 83,
    pace: 72,
    shooting: 76,
    passing: 80,
    dribbling: 80,
    defending: 75,
    physical: 80,
  },
  {
    name: "Alphonso Davies",
    pos: "LI",
    nat: "Canada",
    club: "Bayern Munich",
    overall: 83,
    pace: 94,
    shooting: 66,
    passing: 80,
    dribbling: 85,
    defending: 82,
    physical: 82,
  },
  {
    name: "Exequiel Palacios",
    pos: "MC",
    nat: "Argentina",
    club: "Bayer Leverkusen",
    overall: 83,
    pace: 75,
    shooting: 78,
    passing: 83,
    dribbling: 82,
    defending: 72,
    physical: 74,
  },
  {
    name: "Willi Orbán",
    pos: "DFC",
    nat: "Hungary",
    club: "RB Leipzig",
    overall: 83,
    pace: 70,
    shooting: 40,
    passing: 65,
    dribbling: 55,
    defending: 84,
    physical: 85,
  },
  {
    name: "Alejandro Grimaldo",
    pos: "LI",
    nat: "Spain",
    club: "Bayer Leverkusen",
    overall: 85,
    pace: 78,
    shooting: 78,
    passing: 84,
    dribbling: 85,
    defending: 74,
    physical: 72,
  },
  {
    name: "Marco Carnesecchi",
    pos: "POR",
    nat: "Italy",
    club: "Atalanta",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Josko Gvardiol",
    pos: "DFC",
    nat: "Croatia",
    club: "Manchester City",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Angelo Stiller",
    pos: "MC",
    nat: "Germany",
    club: "Stuttgart",
    overall: 83,
    pace: 66,
    shooting: 74,
    passing: 85,
    dribbling: 80,
    defending: 72,
    physical: 68,
  },
  {
    name: "Oliver Baumann",
    pos: "POR",
    nat: "Germany",
    club: "TSG Hoffenheim",
    overall: 84,
    pace: 44,
    shooting: 14,
    passing: 68,
    dribbling: 36,
    defending: 11,
    physical: 66,
  },
  {
    name: "Aleix García",
    pos: "MC",
    nat: "Spain",
    club: "Bayer Leverkusen",
    overall: 84,
    pace: 68,
    shooting: 72,
    passing: 83,
    dribbling: 80,
    defending: 70,
    physical: 68,
  },
  {
    name: "Dybala",
    pos: "MCO",
    nat: "Argentina",
    club: "Roma",
    overall: 85,
    pace: 78,
    shooting: 84,
    passing: 82,
    dribbling: 88,
    defending: 36,
    physical: 65,
  },
  {
    name: "Maximilian Mittelstädt",
    pos: "LI",
    nat: "Germany",
    club: "Stuttgart",
    overall: 83,
    pace: 80,
    shooting: 60,
    passing: 76,
    dribbling: 78,
    defending: 74,
    physical: 70,
  },
  {
    name: "Felix Nmecha",
    pos: "MC",
    nat: "Germany",
    club: "Borussia Dortmund",
    overall: 84,
    pace: 75,
    shooting: 72,
    passing: 78,
    dribbling: 80,
    defending: 68,
    physical: 75,
  },
  {
    name: "Lobotka",
    pos: "MCD",
    nat: "Slovakia",
    club: "Napoli",
    overall: 83,
    pace: 65,
    shooting: 62,
    passing: 84,
    dribbling: 83,
    defending: 78,
    physical: 68,
  },
  {
    name: "Hugo Ekitike",
    pos: "DC",
    nat: "France",
    club: "Liverpool",
    overall: 85,
    pace: 90,
    shooting: 86,
    passing: 65,
    dribbling: 82,
    defending: 25,
    physical: 85,
  },
];

// DRAFT_STARS: real players with verified overall = 86
exports.DRAFT_STARS = [
  {
    name: "Bruno Guimarães",
    pos: "MC",
    nat: "Brazil",
    club: "Newcastle United",
    overall: 86,
    pace: 73,
    shooting: 73,
    passing: 84,
    dribbling: 81,
    defending: 84,
    physical: 80,
  },
  {
    name: "Cole Palmer",
    pos: "MCO",
    nat: "England",
    club: "Chelsea",
    overall: 86,
    pace: 80,
    shooting: 83,
    passing: 82,
    dribbling: 88,
    defending: 42,
    physical: 68,
  },
  {
    name: "Nico Schlotterbeck",
    pos: "DFC",
    nat: "Germany",
    club: "Dortmund",
    overall: 86,
    pace: 81,
    shooting: 43,
    passing: 72,
    dribbling: 65,
    defending: 84,
    physical: 83,
  },
  {
    name: "Martin Ødegaard",
    pos: "MCO",
    nat: "Norway",
    club: "Arsenal",
    overall: 86,
    pace: 73,
    shooting: 80,
    passing: 88,
    dribbling: 88,
    defending: 60,
    physical: 64,
  },
  {
    name: "Scott McTominay",
    pos: "MC",
    nat: "Scotland",
    club: "Napoli",
    overall: 86,
    pace: 81,
    shooting: 43,
    passing: 72,
    dribbling: 65,
    defending: 84,
    physical: 83,
  },
  {
    name: "Dayot Upamecano",
    pos: "DFC",
    nat: "France",
    club: "Bayern Munich",
    overall: 86,
    pace: 81,
    shooting: 44,
    passing: 70,
    dribbling: 63,
    defending: 85,
    physical: 86,
  },
  {
    name: "Bremer",
    pos: "DFC",
    nat: "Brazil",
    club: "Juventus",
    overall: 86,
    pace: 81,
    shooting: 43,
    passing: 72,
    dribbling: 65,
    defending: 84,
    physical: 83,
  },
  {
    name: "Viktor Gyökeres",
    pos: "DC",
    nat: "Sweden",
    club: "Arsenal",
    overall: 86,
    pace: 84,
    shooting: 88,
    passing: 70,
    dribbling: 82,
    defending: 35,
    physical: 86,
  },
  {
    name: "Ryan Gravenberch",
    pos: "MCD",
    nat: "Netherlands",
    club: "Liverpool",
    overall: 86,
    pace: 81,
    shooting: 70,
    passing: 80,
    dribbling: 84,
    defending: 78,
    physical: 78,
  },
  {
    name: "Dominik Szoboszlai",
    pos: "MCO",
    nat: "Hungary",
    club: "Liverpool",
    overall: 86,
    pace: 80,
    shooting: 81,
    passing: 85,
    dribbling: 84,
    defending: 62,
    physical: 78,
  },
  {
    name: "Victor Osimhen",
    pos: "DC",
    nat: "Nigeria",
    club: "Galatasaray",
    overall: 86,
    pace: 90,
    shooting: 86,
    passing: 65,
    dribbling: 82,
    defending: 25,
    physical: 85,
  },
  {
    name: "Federico Dimarco",
    pos: "LI",
    nat: "Italy",
    club: "Inter Milan",
    overall: 86,
    pace: 78,
    shooting: 74,
    passing: 84,
    dribbling: 80,
    defending: 80,
    physical: 75,
  },
  {
    name: "Hakan Çalhanoğlu",
    pos: "MCD",
    nat: "Turkey",
    club: "Inter Milan",
    overall: 86,
    pace: 65,
    shooting: 82,
    passing: 88,
    dribbling: 85,
    defending: 65,
    physical: 75,
  },
  {
    name: "Désiré Doué",
    pos: "ED",
    nat: "France",
    club: "PSG",
    overall: 86,
    pace: 84,
    shooting: 80,
    passing: 78,
    dribbling: 89,
    defending: 52,
    physical: 76,
  },
  {
    name: "Lionel Messi",
    pos: "MCO",
    nat: "Argentina",
    club: "Inter Miami",
    overall: 86,
    pace: 77,
    shooting: 85,
    passing: 86,
    dribbling: 89,
    defending: 34,
    physical: 66,
  },
  {
    name: "Jules Koundé",
    pos: "LD",
    nat: "France",
    club: "Barcelona",
    overall: 86,
    pace: 84,
    shooting: 55,
    passing: 74,
    dribbling: 78,
    defending: 83,
    physical: 85,
  },
  {
    name: "Robert Lewandowski",
    pos: "DC",
    nat: "Poland",
    club: "Barcelona",
    overall: 86,
    pace: 71,
    shooting: 88,
    passing: 78,
    dribbling: 83,
    defending: 48,
    physical: 83,
  },
  {
    name: "Julián Álvarez",
    pos: "DC",
    nat: "Argentina",
    club: "Atletico de Madrid",
    overall: 86,
    pace: 86,
    shooting: 86,
    passing: 83,
    dribbling: 87,
    defending: 63,
    physical: 82,
  },
];

// SQUAD_POOL: real players with verified overall in 80-82 range
exports.SQUAD_POOL = [
  { name: "Madueke", pos: "ED", nat: "England", club: "Arsenal", overall: 80 },
  {
    name: "Murillo",
    pos: "DFC",
    nat: "Brazil",
    club: "Nottingham Forest",
    overall: 82,
  },
  {
    name: "Robin Koch",
    pos: "DFC",
    nat: "Germany",
    club: "Eintracht Frankfurt",
    overall: 80,
  },
  {
    name: "Nico O'Reilly",
    pos: "LI",
    nat: "England",
    club: "Manchester City",
    overall: 81,
  },
  {
    name: "Álvaro Carreras",
    pos: "LI",
    nat: "Spain",
    club: "Real Madrid",
    overall: 81,
  },
  {
    name: "Lewis Hall",
    pos: "LI",
    nat: "England",
    club: "Newcastle United",
    overall: 81,
  },
  {
    name: "Miguel Gutiérrez",
    pos: "LI",
    nat: "Spain",
    club: "Napoli",
    overall: 81,
  },
  {
    name: "Milos Kerkez",
    pos: "LI",
    nat: "Hungary",
    club: "Liverpool",
    overall: 81,
  },
  {
    name: "Antonee Robinson",
    pos: "LI",
    nat: "United States",
    club: "Fulham",
    overall: 81,
  },
  {
    name: "Lucas Hernández",
    pos: "LI",
    nat: "France",
    club: "PSG",
    overall: 81,
  },
  {
    name: "Ferland Mendy",
    pos: "LI",
    nat: "France",
    club: "Real Madrid",
    overall: 81,
  },
  {
    name: "Nathaniel Brown",
    pos: "LI",
    nat: "Germany",
    club: "Eintracht Frankfurt",
    overall: 80,
  },
  {
    name: "Andrea Cambiaso",
    pos: "LI",
    nat: "Italy",
    club: "Juventus",
    overall: 80,
  },
  {
    name: "Neco Williams",
    pos: "LI",
    nat: "Wales",
    club: "Nottingham Forest",
    overall: 80,
  },
  {
    name: "Mattia Zacagni",
    pos: "EI",
    nat: "Italy",
    club: "Lazio",
    overall: 83,
  },
  {
    name: "Rodrigo de Paul",
    pos: "MC",
    nat: "Argentina",
    club: "Inter Miami",
    overall: 83,
  },
  {
    name: "Leandro Trossard",
    pos: "EI",
    nat: "Belgium",
    club: "Arsenal",
    overall: 83,
  },
  {
    name: "Reinildo",
    pos: "LI",
    nat: "Mozambique",
    club: "Sunderland",
    overall: 80,
  },
  {
    name: "Matthieu Udol",
    pos: "LI",
    nat: "France",
    club: "RC Lens",
    overall: 80,
  },
  {
    name: "Leonardo Spinazzola",
    pos: "LI",
    nat: "Italy",
    club: "Napoli",
    overall: 80,
  },
  {
    name: "Lucas Digne",
    pos: "LI",
    nat: "France",
    club: "Aston Villa",
    overall: 80,
  },
  {
    name: "Jeremie Frimpong",
    pos: "LD",
    nat: "Netherlands",
    club: "Liverpool",
    overall: 82,
  },
  {
    name: "Matheus Nunes",
    pos: "LD",
    nat: "Portugal",
    club: "Manchester City",
    overall: 82,
  },
  {
    name: "Pedro Porro",
    pos: "LD",
    nat: "Spain",
    club: "Tottenham",
    overall: 82,
  },
  {
    name: "Ollie Watkins",
    pos: "DC",
    nat: "England",
    club: "Aston Villa",
    overall: 82,
  },
  {
    name: "Igor Thiago",
    pos: "DC",
    nat: "Brazil",
    club: "Brentford",
    overall: 82,
  },
  {
    name: "Dusan Vlahovic",
    pos: "DC",
    nat: "Serbia",
    club: "Juventus",
    overall: 81,
  },
  {
    name: "Jonathan David",
    pos: "DC",
    nat: "Canada",
    club: "Juventus",
    overall: 81,
  },
  {
    name: "Yoane Wissa",
    pos: "DC",
    nat: "Republic of the Congo",
    club: "Newcastle United",
    overall: 81,
  },
  {
    name: "Vedat Muriqi",
    pos: "DC",
    nat: "Kosovo",
    club: "Mallorca",
    overall: 81,
  },
  {
    name: "Ayoze",
    pos: "DC",
    nat: "Spain",
    club: "Villarreal",
    overall: 81,
  },
  {
    name: "Aubameyang",
    pos: "DC",
    nat: "Gabon",
    club: "Olympique Marseille",
    overall: 81,
  },
  {
    name: "Gonçalo Ramos",
    pos: "DC",
    nat: "Portugal",
    club: "PSG",
    overall: 80,
  },
  {
    name: "Nick Woltemade",
    pos: "DC",
    nat: "Germany",
    club: "Newcastle United",
    overall: 80,
  },
  {
    name: "Luis Suárez",
    pos: "DC",
    nat: "Colombia",
    club: "Sporting CP",
    overall: 80,
  },
  {
    name: "Youssef en-Nessyri",
    pos: "DC",
    nat: "Morocco",
    club: "Al Ittihad",
    overall: 80,
  },
  {
    name: "Gabriel Jesus",
    pos: "DC",
    nat: "Brazil",
    club: "Arsenal",
    overall: 80,
  },
  {
    name: "Daniel Muñoz",
    pos: "LD",
    nat: "Colombia",
    club: "Crystal Palace",
    overall: 82,
  },
  {
    name: "Ben White",
    pos: "LD",
    nat: "England",
    club: "Arsenal",
    overall: 82,
  },
  {
    name: "Matty Cash",
    pos: "LD",
    nat: "Poland",
    club: "Aston Villa",
    overall: 81,
  },
  {
    name: "Michael Kayode",
    pos: "LD",
    nat: "Italy",
    club: "Brentford",
    overall: 80,
  },
  {
    name: "Tino Livramento",
    pos: "LD",
    nat: "England",
    club: "Newcastle United",
    overall: 80,
  },
  {
    name: "Óscar Mingueza",
    pos: "LD",
    nat: "Spain",
    club: "Celta",
    overall: 80,
  },
  {
    name: "Andrei Ratiu",
    pos: "LD",
    nat: "Romania",
    club: "Rayo Vallecano",
    overall: 80,
  },
  {
    name: "Noussair Mazraoui",
    pos: "LD",
    nat: "Morocco",
    club: "Manchester United",
    overall: 80,
  },
  {
    name: "Julian Ryerson",
    pos: "LD",
    nat: "Norway",
    club: "Borussia Dortmund",
    overall: 80,
  },
  {
    name: "Benjamin Henrichs",
    pos: "LD",
    nat: "Germany",
    club: "RB Leipzig",
    overall: 80,
  },
  {
    name: "Ola Aina",
    pos: "LD",
    nat: "Nigeria",
    club: "Nottingham Forest",
    overall: 80,
  },
  {
    name: "Aleksandar Pavlović",
    pos: "MCD",
    nat: "Germany",
    club: "Bayern Munich",
    overall: 82,
  },
  {
    name: "Éderson",
    pos: "MC",
    nat: "Brazil",
    club: "Atalanta",
    overall: 82,
  },
  {
    name: "Nico Paz",
    pos: "MCO",
    nat: "Argentina",
    club: "Como",
    overall: 82,
  },
  {
    name: "Elliot Anderson",
    pos: "MCD",
    nat: "England",
    club: "Nottingham Forest",
    overall: 82,
  },
  {
    name: "Carlos Augusto",
    pos: "LI",
    nat: "Brazil",
    club: "Inter Milan",
    overall: 81,
  },
  {
    name: "Rayan Aït-Nouri",
    pos: "LI",
    nat: "Algeria",
    club: "Manchester City",
    overall: 81,
  },
  {
    name: "Ritsu Doan",
    pos: "ED",
    nat: "Japan",
    club: "Eintracht Frankfurt",
    overall: 81,
  },
  {
    name: "Jonathan Burkardt",
    pos: "DC",
    nat: "Germany",
    club: "Eintracht Frankfurt",
    overall: 82,
  },
  {
    name: "Lukebakio",
    pos: "ED",
    nat: "Belgium",
    club: "Benfica",
    overall: 81,
  },
  {
    name: "Vivian",
    pos: "DFC",
    nat: "Spain",
    club: "Athletic Club",
    overall: 82,
  },
  {
    name: "Gonçalo Inácio",
    pos: "DFC",
    nat: "Portugal",
    club: "Sporting CP",
    overall: 81,
  },
  {
    name: "Malick Thiaw",
    pos: "DFC",
    nat: "Germany",
    club: "Newcastle United",
    overall: 81,
  },
  {
    name: "Ronald Araújo",
    pos: "DFC",
    nat: "Uruguay",
    club: "Barcelona",
    overall: 81,
  },
  {
    name: "Sven Botman",
    pos: "DFC",
    nat: "Netherlands",
    club: "Newcastle United",
    overall: 81,
  },
  {
    name: "Nayef Aguerd",
    pos: "DFC",
    nat: "Morocco",
    club: "Olympique Marseille",
    overall: 81,
  },
  {
    name: "Maxence Lacroix",
    pos: "DFC",
    nat: "France",
    club: "Crystal Palace",
    overall: 81,
  },
  {
    name: "Edmond Tapsoba",
    pos: "DFC",
    nat: "Burkina Faso",
    club: "Bayer Leverkusen",
    overall: 82,
  },
  {
    name: "Ibañez",
    pos: "DFC",
    nat: "Brazil",
    club: "Al Ahli",
    overall: 82,
  },
  {
    name: "Alessandro Buongiorno",
    pos: "DFC",
    nat: "Italy",
    club: "Napoli",
    overall: 82,
  },
  {
    name: "Kim Min-jae",
    pos: "DFC",
    nat: "South Korea",
    club: "Bayern Munich",
    overall: 82,
  },
  {
    name: "Riccardo Calafiori",
    pos: "LI",
    nat: "Italy",
    club: "Arsenal",
    overall: 82,
  },
  {
    name: "Gabriel Martinelli",
    pos: "EI",
    nat: "Brazil",
    club: "Arsenal",
    overall: 81,
  },
  {
    name: "Lucas Chevalier",
    pos: "POR",
    nat: "France",
    club: "PSG",
    overall: 82,
  },
  {
    name: "Matvey Safonov",
    pos: "POR",
    nat: "Russia",
    club: "PSG",
    overall: 82,
  },
  {
    name: "Dean Henderson",
    pos: "POR",
    nat: "England",
    club: "Crystal Palace",
    overall: 82,
  },
  {
    name: "Álex Remiro",
    pos: "POR",
    nat: "Spain",
    club: "Real Sociedad",
    overall: 82,
  },
  {
    name: "Alex Meret",
    pos: "POR",
    nat: "Italy",
    club: "Napoli",
    overall: 82,
  },
  {
    name: "Wladimiro Falcone",
    pos: "POR",
    nat: "Italy",
    club: "Lecce",
    overall: 82,
  },
  {
    name: "Manuel Neuer",
    pos: "POR",
    nat: "Germany",
    club: "Bayern Munich",
    overall: 82,
  },
  {
    name: "Guglielmo Vicario",
    pos: "POR",
    nat: "Italy",
    club: "Tottenham",
    overall: 81,
  },
  {
    name: "Sam Lammens",
    pos: "POR",
    nat: "Belgium",
    club: "Manchester United",
    overall: 81,
  },
  {
    name: "Michele di Gregorio",
    pos: "POR",
    nat: "Italy",
    club: "Juventus",
    overall: 81,
  },
  {
    name: "Édouard Mendy",
    pos: "POR",
    nat: "Senegal",
    club: "Al Ahli",
    overall: 81,
  },
  {
    name: "Koen Casteels",
    pos: "POR",
    nat: "Belgium",
    club: "Al Qadsiah",
    overall: 82,
  },
  {
    name: "Jurriën Timber",
    pos: "LD",
    nat: "Netherlands",
    club: "Arsenal",
    overall: 82,
  },
  {
    name: "Gabriel Jesus",
    pos: "DC",
    nat: "Brazil",
    club: "Arsenal",
    overall: 80,
  },
  {
    name: "Matthijs de Ligt",
    pos: "DFC",
    nat: "Netherlands",
    club: "Manchester United",
    overall: 82,
  },
  {
    name: "Lisandro Martínez",
    pos: "DFC",
    nat: "Argentina",
    club: "Manchester United",
    overall: 81,
  },
  {
    name: "Antony",
    pos: "ED",
    nat: "Brazil",
    club: "Manchester United",
    overall: 81,
  },
  {
    name: "Mohammed Kudus",
    pos: "ED",
    nat: "Ghana",
    club: "Tottenham",
    overall: 81,
  },
  {
    name: "Takefusa Kubo",
    pos: "ED",
    nat: "Japan",
    club: "Real Sociedad",
    overall: 81,
  },
  {
    name: "Ismaïla Sarr",
    pos: "ED",
    nat: "Senegal",
    club: "Crystal Palace",
    overall: 82,
  },
  {
    name: "Brahim Díaz",
    pos: "ED",
    nat: "Morocco",
    club: "Real Madrid",
    overall: 81,
  },
  {
    name: "Nicolas Pépé",
    pos: "ED",
    nat: "Ivory Coast",
    club: "Villarreal",
    overall: 81,
  },
  {
    name: "Matteo Politano",
    pos: "ED",
    nat: "Italy",
    club: "Napoli",
    overall: 81,
  },
  {
    name: "Iñaki Williams",
    pos: "ED",
    nat: "Ghana",
    club: "Athletic Club",
    overall: 81,
  },
  {
    name: "Florian Thauvin",
    pos: "ED",
    nat: "France",
    club: "RC Lens",
    overall: 81,
  },
  {
    name: "Marc Pubill",
    pos: "DFC",
    nat: "Spain",
    club: "Atletico de Madrid",
    overall: 80,
  },
  {
    name: "Federico Chiesa",
    pos: "ED",
    nat: "Italy",
    club: "Liverpool",
    overall: 80,
  },
  {
    name: "Donyell Malen",
    pos: "DC",
    nat: "Netherlands",
    club: "Roma",
    overall: 80,
  },
  {
    name: "Isi Palazón",
    pos: "MCO",
    nat: "Spain",
    club: "Rayo Vallecano",
    overall: 80,
  },
  {
    name: "James Rodriguez",
    pos: "MCO",
    nat: "Colombia",
    club: "Free Agent",
    overall: 80,
  },
  {
    name: "Marco Asensio",
    pos: "MCO",
    nat: "Spain",
    club: "Fenerbahçe",
    overall: 80,
  },
  {
    name: "João Pedro",
    pos: "DC",
    nat: "Brazil",
    club: "Chelsea",
    overall: 82,
  },
  {
    name: "Deniz Undav",
    pos: "DC",
    nat: "Germany",
    club: "Stuttgart",
    overall: 82,
  },
  {
    name: "Loïs Openda",
    pos: "DC",
    nat: "Belgium",
    club: "Juventus",
    overall: 82,
  },
  {
    name: "Jean-Philippe Mateta",
    pos: "DC",
    nat: "France",
    club: "Crystal Palace",
    overall: 82,
  },

  {
    name: "Thomas Müller",
    pos: "MCO",
    nat: "Germany",
    club: "Vancouver Whitecaps",
    overall: 80,
  },
  {
    name: "Casemiro",
    pos: "MCD",
    nat: "Brazil",
    club: "Manchester United",
    overall: 82,
  },
  {
    name: "Harry Maguire",
    pos: "DFC",
    nat: "England",
    club: "Manchester United",
    overall: 80,
  },
  {
    name: "Jadon Sancho",
    pos: "EI",
    nat: "England",
    club: "Manchester United",
    overall: 80,
  },
  {
    name: "Noussair Mazraoui",
    pos: "LD",
    nat: "Morocco",
    club: "Manchester United",
    overall: 80,
  },
  {
    name: "Benjamin Šeško",
    pos: "DC",
    nat: "Slovenia",
    club: "Manchester United",
    overall: 80,
  },
  {
    name: "André Onana",
    pos: "POR",
    nat: "Cameroon",
    club: "Manchester United",
    overall: 80,
  },
  {
    name: "Andy Robertson",
    pos: "LI",
    nat: "Scotland",
    club: "Liverpool",
    overall: 82,
  },
  {
    name: "Milos Kerkez",
    pos: "LI",
    nat: "Hungary",
    club: "Liverpool",
    overall: 82,
  },
  {
    name: "Federico Chiesa",
    pos: "ED",
    nat: "Italy",
    club: "Liverpool",
    overall: 81,
  },
  {
    name: "Carlos Augusto",
    pos: "LI",
    nat: "Brazil",
    club: "Inter Milan",
    overall: 81,
  },
  {
    name: "Matteo Darmian",
    pos: "LD",
    nat: "Italy",
    club: "Inter Milan",
    overall: 81,
  },
  {
    name: "Davide Frattesi",
    pos: "MC",
    nat: "Italy",
    club: "Inter Milan",
    overall: 81,
  },
  {
    name: "Youssouf Fofana",
    pos: "MCD",
    nat: "France",
    club: "AC Milan",
    overall: 81,
  },
  {
    name: "Kai Havertz",
    pos: "DC",
    nat: "Germany",
    club: "Arsenal",
    overall: 82,
  },
  {
    name: "Xavi Simons",
    pos: "MCO",
    nat: "Netherlands",
    club: "Tottenham",
    overall: 82,
  },
  {
    name: "Pape Matar Sarr",
    pos: "MCD",
    nat: "Senegal",
    club: "Tottenham",
    overall: 80,
  },
  {
    name: "Micky van de Ven",
    pos: "DFC",
    nat: "Netherlands",
    club: "Tottenham",
    overall: 82,
  },
  {
    name: "Jeremie Frimpong",
    pos: "LD",
    nat: "Netherlands",
    club: "Liverpool",
    overall: 82,
  },
  {
    name: "Fikayo Tomori",
    pos: "DFC",
    nat: "England",
    club: "AC Milan",
    overall: 81,
  },
  {
    name: "Kenan Yıldız",
    pos: "MCO",
    nat: "Turkey",
    club: "Juventus",
    overall: 82,
  },
  {
    name: "Charles De Ketelaere",
    pos: "MCO",
    nat: "Belgium",
    club: "Atalanta",
    overall: 82,
  },
  {
    name: "Oihan Sancet",
    pos: "MCO",
    nat: "Spain",
    club: "Athletic Club",
    overall: 82,
  },
  {
    name: "Orkun Kökçü",
    pos: "MC",
    nat: "Turkey",
    club: "Besiktas",
    overall: 82,
  },
  {
    name: "Matteo Guendouzi",
    pos: "MC",
    nat: "France",
    club: "Fenerbahçe",
    overall: 82,
  },
  {
    name: "Corentin Tolisso",
    pos: "MC",
    nat: "France",
    club: "Olympique Lyonnais",
    overall: 82,
  },
  {
    name: "Rafa Silva",
    pos: "MCO",
    nat: "Portugal",
    club: "Benfica",
    overall: 82,
  },
  {
    name: "Mateo Kovačić",
    pos: "MC",
    nat: "Croatia",
    club: "Manchester City",
    overall: 82,
  },
  {
    name: "Konstantinos Fortounis",
    pos: "MCO",
    nat: "Greece",
    club: "Al Khaleej",
    overall: 82,
  },
  {
    name: "Joey Veerman",
    pos: "MC",
    nat: "Netherlands",
    club: "PSV",
    overall: 81,
  },
  {
    name: "Moleiro",
    pos: "EI",
    nat: "Spain",
    club: "Villarreal",
    overall: 82,
  },
  {
    name: "Iliman Ndiaye",
    pos: "EI",
    nat: "Senegal",
    club: "Everton",
    overall: 82,
  },
  {
    name: "Álex Baena",
    pos: "EI",
    nat: "Spain",
    club: "Atletico de Madrid",
    overall: 82,
  },
  {
    name: "Giuliano Simeone",
    pos: "ED",
    nat: "Argentina",
    club: "Atletico de Madrid",
    overall: 82,
  },
  {
    name: "Karim Adeyemi",
    pos: "ED",
    nat: "Germany",
    club: "Borussia Dortmund",
    overall: 82,
  },
  {
    name: "Anthony Gordon",
    pos: "EI",
    nat: "England",
    club: "Newcastle United",
    overall: 82,
  },
  {
    name: "Pedro Neto",
    pos: "ED",
    nat: "Portugal",
    club: "Chelsea",
    overall: 82,
  },
  {
    name: "Marcus Rashford",
    pos: "EI",
    nat: "England",
    club: "Barcelona",
    overall: 82,
  },
  {
    name: "Kinglsey Coman",
    pos: "ED",
    nat: "France",
    club: "Al Nassr",
    overall: 82,
  },
  {
    name: "Savinho",
    pos: "ED",
    nat: "Brazil",
    club: "Manchester City",
    overall: 81,
  },
  {
    name: "Jack Grealish",
    pos: "EI",
    nat: "England",
    club: "Everton",
    overall: 82,
  },
  {
    name: "Mitoma",
    pos: "EI",
    nat: "Japan",
    club: "Brighton",
    overall: 81,
  },
  {
    name: "David Neres",
    pos: "EI",
    nat: "Brazil",
    club: "Napoli",
    overall: 81,
  },
  {
    name: "Leroy Sané",
    pos: "ED",
    nat: "Germany",
    club: "Galatasaray",
    overall: 81,
  },
  {
    name: "Álvaro García",
    pos: "EI",
    nat: "Spain",
    club: "Rayo Vallecano",
    overall: 81,
  },
  {
    name: "Yannick Carrasco",
    pos: "EI",
    nat: "Belgium",
    club: "Al Shabab",
    overall: 81,
  },
  {
    name: "Yan Diomandé",
    pos: "ED",
    nat: "Ivory Coast",
    club: "RB Leipzig",
    overall: 81,
  },
  {
    name: "Abde",
    pos: "EI",
    nat: "Morocco",
    club: "Real Betis",
    overall: 80,
  },
  {
    name: "Malcom",
    pos: "ED",
    nat: "Brazil",
    club: "Al Hilal",
    overall: 82,
  },
  {
    name: "Domenico Berardi",
    pos: "ED",
    nat: "Italy",
    club: "Sassuolo",
    overall: 82,
  },
  {
    name: "Iago Aspas",
    pos: "ED",
    nat: "Spain",
    club: "Celta",
    overall: 82,
  },
  {
    name: "Memphis Depay",
    pos: "DC",
    nat: "Netherlands",
    club: "Free Agent",
    overall: 80,
  },
  {
    name: "Eduardo Camavinga",
    pos: "MC",
    nat: "France",
    club: "Real Madrid",
    overall: 81,
  },
  {
    name: "Khéphren Thuram",
    pos: "MC",
    nat: "France",
    club: "Juventus",
    overall: 81,
  },
  {
    name: "João Félix",
    pos: "MCO",
    nat: "Portugal",
    club: "Al Nassr",
    overall: 81,
  },
  { name: "Luis Milla", pos: "MC", nat: "Spain", club: "Getafe", overall: 81 },
  {
    name: "Christoph Baumgartner",
    pos: "MCO",
    nat: "Austria",
    club: "RB Leipzig",
    overall: 81,
  },
  {
    name: "Morgan Gibbs-White",
    pos: "MCO",
    nat: "England",
    club: "Nottingham Forest",
    overall: 81,
  },
  {
    name: "Christopher Nkunku",
    pos: "MCO",
    nat: "France",
    club: "AC Milan",
    overall: 81,
  },
  {
    name: "Pablo Fornals",
    pos: "MC",
    nat: "Spain",
    club: "Real Betis",
    overall: 81,
  },
  {
    name: "Giovani Lo Celso",
    pos: "MCO",
    nat: "Argentina",
    club: "Real Betis",
    overall: 81,
  },
  {
    name: "Joelinton",
    pos: "MC",
    nat: "Brazil",
    club: "Newcastle United",
    overall: 81,
  },
  {
    name: "Andrej Kramarić",
    pos: "MCO",
    nat: "Croatia",
    club: "TSG Hoffenheim",
    overall: 81,
  },
  {
    name: "Ricardo Horta",
    pos: "MCO",
    nat: "Portugal",
    club: "Sporting CP",
    overall: 81,
  },
  {
    name: "Anderson Talisca",
    pos: "MCO",
    nat: "Brazil",
    club: "Fenerbahçe",
    overall: 81,
  },
  {
    name: "Otávio",
    pos: "MC",
    nat: "Portugal",
    club: "Al Qadsiah FC",
    overall: 81,
  },
  {
    name: "Marten de Roon",
    pos: "MC",
    nat: "Netherlands",
    club: "Atalanta",
    overall: 81,
  },
  {
    name: "Bryan Cristante",
    pos: "MC",
    nat: "Italy",
    club: "Roma",
    overall: 81,
  },
  {
    name: "Leandro Paredes",
    pos: "MC",
    nat: "Argentina",
    club: "Boca Juniors",
    overall: 81,
  },
  {
    name: "Hans Vanaken",
    pos: "MCO",
    nat: "Belgium",
    club: "Club Brugge",
    overall: 81,
  },
  {
    name: "Koke",
    pos: "MC",
    nat: "Spain",
    club: "Atletico de Madrid",
    overall: 81,
  },
  {
    name: "Mikel Jauregizar",
    pos: "MC",
    nat: "Spain",
    club: "Athletic Club",
    overall: 81,
  },
  {
    name: "Andrey Santos",
    pos: "MC",
    nat: "Brazil",
    club: "Chelsea",
    overall: 81,
  },
  {
    name: "Gabriel Sara",
    pos: "MC",
    nat: "Brazil",
    club: "Galatasaray",
    overall: 80,
  },
  {
    name: "Maghnes Akliouche",
    pos: "MCO",
    nat: "France",
    club: "AS Monaco",
    overall: 80,
  },
  {
    name: "Ismael Saibari",
    pos: "MCO",
    nat: "Morocco",
    club: "PSV",
    overall: 80,
  },
  {
    name: "Piotr Zieliński",
    pos: "MCO",
    nat: "Poland",
    club: "Inter Milan",
    overall: 80,
  },
  {
    name: "Pau Torres",
    pos: "DFC",
    nat: "Spain",
    club: "Aston Villa",
    overall: 81,
  },
  {
    name: "Marc Guéhi",
    pos: "DFC",
    nat: "England",
    club: "Crystal Palace",
    overall: 82,
  },
  {
    name: "Palhinha",
    pos: "MCD",
    nat: "Portugal",
    club: "Tottenham",
    overall: 82,
  },
  {
    name: "Lucas Torreira",
    pos: "MCD",
    nat: "Uruguay",
    club: "Galatasaray",
    overall: 82,
  },
  {
    name: "Fabinho",
    pos: "MCD",
    nat: "Brazil",
    club: "Al Ittihad",
    overall: 82,
  },
  {
    name: "Remo Freuler",
    pos: "MCD",
    nat: "Switzerland",
    club: "Bologna",
    overall: 82,
  },
  {
    name: "Serge Gnabry",
    pos: "MCO",
    nat: "Germany",
    club: "Bayern Munich",
    overall: 83,
  },
  {
    name: "Adam Wharton",
    pos: "MCD",
    nat: "England",
    club: "Crystal Palace",
    overall: 81,
  },
  {
    name: "Amadou Onana",
    pos: "MCD",
    nat: "Belgium",
    club: "Aston Villa",
    overall: 81,
  },
  {
    name: "Nico González",
    pos: "MCD",
    nat: "Spain",
    club: "Manchester City",
    overall: 81,
  },
  {
    name: "Pedro Porro",
    pos: "LD",
    nat: "Spain",
    club: "Tottenham",
    overall: 82,
  },
  {
    name: "Cristian Romero",
    pos: "DFC",
    nat: "Argentina",
    club: "Tottenham",
    overall: 82,
  },
  {
    name: "Yassine Bounou",
    pos: "POR",
    nat: "Morocco",
    club: "Al-Hilal",
    overall: 82,
  },
  {
    name: "Alessio Romagnoli",
    pos: "DFC",
    nat: "Italy",
    club: "Lazio",
    overall: 82,
  },
  {
    name: "Fabian Schär",
    pos: "DFC",
    nat: "Switzerland",
    club: "Newcastle United",
    overall: 82,
  },
  {
    name: "Nathan Aké",
    pos: "DFC",
    nat: "Netherlands",
    club: "Manchester City",
    overall: 82,
  },
  {
    name: "Emre Can",
    pos: "DFC",
    nat: "Germany",
    club: "Borussia Dortmund",
    overall: 82,
  },
  {
    name: "John Stones",
    pos: "DFC",
    nat: "England",
    club: "Manchester City",
    overall: 82,
  },
  {
    name: "Kalidou Koulibaly",
    pos: "DFC",
    nat: "Senegal",
    club: "Al Hilal",
    overall: 82,
  },
  {
    name: "Thiago Silva",
    pos: "DFC",
    nat: "Brazil",
    club: "Porto",
    overall: 82,
  },
  {
    name: "Mario Gila",
    pos: "DFC",
    nat: "Spain",
    club: "Lazio",
    overall: 81,
  },
  {
    name: "Castello Lukeba",
    pos: "DFC",
    nat: "France",
    club: "RB Leipzig",
    overall: 81,
  },
  {
    name: "Aymeric Laporte",
    pos: "DFC",
    nat: "Spain",
    club: "Athletic Club",
    overall: 82,
  },
  {
    name: "Robin Le Normand",
    pos: "DFC",
    nat: "Spain",
    club: "Atletico de Madrid",
    overall: 81,
  },
  {
    name: "Dean Huijsen",
    pos: "DFC",
    nat: "Spain",
    club: "Real Madrid",
    overall: 81,
  },
];

// LEGEND_POOL: LEGENDS of the game
exports.LEGEND_POOL = [
  {
    name: "Toni Kroos",
    pos: "MC",
    nat: "Germany",
    club: "Legend",
    overall: 90,
  },
  {
    name: "Raúl",
    pos: "DC",
    nat: "Spain",
    club: "Legend",
    overall: 90,
  },
  {
    name: "Iker Casillas",
    pos: "POR",
    nat: "Spain",
    club: "Legend",
    overall: 90,
  },
  {
    name: "Rivaldo",
    pos: "EI",
    nat: "Brazil",
    club: "Legend",
    overall: 90,
  },
  {
    name: "Andrea Pirlo",
    pos: "MC",
    nat: "Italy",
    club: "Legend",
    overall: 90,
  },
  {
    name: "Dennis Bergkamp",
    pos: "DC",
    nat: "Netherlands",
    club: "Legend",
    overall: 90,
  },
  {
    name: "Xavi",
    pos: "MC",
    nat: "Spain",
    club: "Legend",
    overall: 91,
  },
  {
    name: "Oliver Kahn",
    pos: "POR",
    nat: "Germany",
    club: "Legend",
    overall: 91,
  },
  {
    name: "Thierry Henry",
    pos: "DC",
    nat: "France",
    club: "Legend",
    overall: 91,
  },
  {
    name: "Zlatan Ibrahimovic",
    pos: "DC",
    nat: "Sweden",
    club: "Legend",
    overall: 91,
  },
  {
    name: "Ronaldo Nazario",
    pos: "DC",
    nat: "Brazil",
    club: "Legend",
    overall: 94,
  },
  {
    name: "Zinedine Zidane",
    pos: "MCO",
    nat: "France",
    club: "Legend",
    overall: 93,
  },
  {
    name: "Andrés Iniesta",
    pos: "MC",
    nat: "Spain",
    club: "Legend",
    overall: 92,
  },
  {
    name: "Roberto Baggio",
    pos: "MCO",
    nat: "Italy",
    club: "Legend",
    overall: 91,
  },
  {
    name: "Gianluca Vialli",
    pos: "DC",
    nat: "Italy",
    club: "Legend",
    overall: 89,
  },
  {
    name: "Ruud van Nistelrooy",
    pos: "DC",
    nat: "Netherlands",
    club: "Legend",
    overall: 89,
  },
  {
    name: "Lúcio",
    pos: "DFC",
    nat: "Brazil",
    club: "Legend",
    overall: 89,
  },
  {
    name: "Didier Drogba",
    pos: "DC",
    nat: "Ivory Coast",
    club: "Legend",
    overall: 89,
  },
  {
    name: "Philipp Lahm",
    pos: "LD",
    nat: "Germany",
    club: "Legend",
    overall: 89,
  },
  {
    name: "Fernando Morientes",
    pos: "DC",
    nat: "Spain",
    club: "Legend",
    overall: 89,
  },
  {
    name: "Carles Puyol",
    pos: "DFC",
    nat: "Spain",
    club: "Legend",
    overall: 89,
  },
  {
    name: "Samuel Eto'o",
    pos: "DC",
    nat: "Cameroon",
    club: "Legend",
    overall: 89,
  },
  {
    name: "Marcelo",
    pos: "LI",
    nat: "Brazil",
    club: "Legend",
    overall: 89,
  },
  {
    name: "Hristo Stoichkov",
    pos: "DC",
    nat: "Bulgary",
    club: "Legend",
    overall: 89,
  },
  {
    name: "Emilio Butragueño",
    pos: "DC",
    nat: "Spain",
    club: "Legend",
    overall: 89,
  },
  {
    name: "Francesco Totti",
    pos: "DC",
    nat: "Italy",
    club: "Legend",
    overall: 89,
  },
  {
    name: "Kaká",
    pos: "MCO",
    nat: "Brazil",
    club: "Legend",
    overall: 89,
  },
  {
    name: "Alessandro Nesta",
    pos: "DFC",
    nat: "Italy",
    club: "Legend",
    overall: 89,
  },
  {
    name: "Javier Zanetti",
    pos: "LD",
    nat: "Argentina",
    club: "Legend",
    overall: 89,
  },
  {
    name: "Franck Ribéry",
    pos: "EI",
    nat: "France",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Maicon",
    pos: "LD",
    nat: "Brazil",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Ricardo Carvalho",
    pos: "DFC",
    nat: "Portugal",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Patrick Vieira",
    pos: "MC",
    nat: "France",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Diego Milito",
    pos: "DC",
    nat: "Argentina",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Bixente Lizarazu",
    pos: "LI",
    nat: "France",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Lilian Thuram",
    pos: "LD",
    nat: "France",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Petr Cech",
    pos: "POR",
    nat: "Czech Republic",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Jay-Jay Okocha",
    pos: "MCO",
    nat: "Nigeria",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Carlos Tévez",
    pos: "DC",
    nat: "Argentina",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Robin van Persie",
    pos: "DC",
    nat: "Netherlands",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Javier Mascherano",
    pos: "DFC",
    nat: "Argentina",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Gareth Bale",
    pos: "ED",
    nat: "Wales",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Bastian Schweinsteiger",
    pos: "MC",
    nat: "Germany",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Steven Gerrard",
    pos: "MC",
    nat: "England",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Rio Ferdinand",
    pos: "DFC",
    nat: "England",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Vincent Kompany",
    pos: "DFC",
    nat: "Belgium",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Mario Gómez",
    pos: "DC",
    nat: "Germany",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Miroslav Klose",
    pos: "DC",
    nat: "Germany",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Pavel Nedved",
    pos: "EI",
    nat: "Czech Republic",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Giorgio Chiellini",
    pos: "DFC",
    nat: "Italy",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Iván Zamorano",
    pos: "DC",
    nat: "Chile",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Jari Litmanen",
    pos: "MCO",
    nat: "Finland",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Diego Forlán",
    pos: "DC",
    nat: "Uruguay",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Rafa Márquez",
    pos: "DFC",
    nat: "Mexico",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Paolo Futre",
    pos: "EI",
    nat: "Portugal",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Wesley Sneijder",
    pos: "MCO",
    nat: "Netherlands",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Antonio Di Natale",
    pos: "DC",
    nat: "Italy",
    club: "Legend",
    overall: 88,
  },
  {
    name: "Marek Hamsík",
    pos: "MCO",
    nat: "Slovakia",
    club: "Legend",
    overall: 87,
  },
  {
    name: "Rui Costa",
    pos: "MCO",
    nat: "Portugal",
    club: "Legend",
    overall: 87,
  },
  {
    name: "Zé Roberto",
    pos: "EI",
    nat: "Brazil",
    club: "Legend",
    overall: 87,
  },
  {
    name: "Daniele De Rossi",
    pos: "MCD",
    nat: "Italy",
    club: "Legend",
    overall: 87,
  },
  {
    name: "Claudio Marchisio",
    pos: "MC",
    nat: "Italy",
    club: "Legend",
    overall: 87,
  },
  {
    name: "Xabi Alonso",
    pos: "MCD",
    nat: "Spain",
    club: "Legend",
    overall: 87,
  },
  {
    name: "Jaap Stam",
    pos: "DFC",
    nat: "Netherlands",
    club: "Legend",
    overall: 87,
  },
  {
    name: "Iván Córdoba",
    pos: "DFC",
    nat: "Colombia",
    club: "Legend",
    overall: 87,
  },
  {
    name: "Fernando Torres",
    pos: "DC",
    nat: "Spain",
    club: "Legend",
    overall: 87,
  },
  {
    name: "Dimitar Berbatov",
    pos: "DC",
    nat: "Bulgary",
    club: "Legend",
    overall: 87,
  },
  {
    name: "Frank Lampard",
    pos: "MC",
    nat: "England",
    club: "Legend",
    overall: 87,
  },
  {
    name: "Yaya Touré",
    pos: "MC",
    nat: "Ivory Coast",
    club: "Legend",
    overall: 87,
  },
  {
    name: "Nemanja Vidic",
    pos: "DFC",
    nat: "Serbia",
    club: "Legend",
    overall: 87,
  },
  {
    name: "Emmanuel Petit",
    pos: "MCD",
    nat: "France",
    club: "Legend",
    overall: 87,
  },
  {
    name: "Steve McManaman",
    pos: "ED",
    nat: "England",
    club: "Legend",
    overall: 87,
  },
  {
    name: "Ian Wright",
    pos: "DC",
    nat: "England",
    club: "Legend",
    overall: 87,
  },
  {
    name: "Harry Kewell",
    pos: "EI",
    nat: "Australia",
    club: "Legend",
    overall: 87,
  },
  {
    name: "Davor Suker",
    pos: "DC",
    nat: "Croatia",
    club: "Legend",
    overall: 87,
  },
  {
    name: "Gianluca Zambrotta",
    pos: "LD",
    nat: "Italy",
    club: "Legend",
    overall: 86,
  },
  {
    name: "Dirk Kuyt",
    pos: "MCO",
    nat: "Netherlands",
    club: "Legend",
    overall: 86,
  },
  {
    name: "Jerzy Dudek",
    pos: "POR",
    nat: "Poland",
    club: "Legend",
    overall: 86,
  },
  {
    name: "Landon Donovan",
    pos: "MCO",
    nat: "United States",
    club: "Legend",
    overall: 86,
  },
  {
    name: "Ramires",
    pos: "MCD",
    nat: "Brazil",
    club: "Legend",
    overall: 86,
  },
  {
    name: "John Arne Riise",
    pos: "LI",
    nat: "Norway",
    club: "Legend",
    overall: 86,
  },
  {
    name: "Blaise Matuidi",
    pos: "MCD",
    nat: "France",
    club: "Legend",
    overall: 86,
  },
  {
    name: "Joan Capdevila",
    pos: "LI",
    nat: "Spain",
    club: "Legend",
    overall: 86,
  },
  {
    name: "Guti",
    pos: "MC",
    nat: "Spain",
    club: "Legend",
    overall: 86,
  },
  {
    name: "Sidney Govou",
    pos: "DC",
    nat: "France",
    club: "Legend",
    overall: 86,
  },
  {
    name: "Ludovic Giuly",
    pos: "ED",
    nat: "France",
    club: "Legend",
    overall: 86,
  },
  {
    name: "Ole Gunnar Solskjaer",
    pos: "DC",
    nat: "Norway",
    club: "Legend",
    overall: 86,
  },
  {
    name: "Park Ji Sung",
    pos: "EI",
    nat: "South Korea",
    club: "Legend",
    overall: 86,
  },
  {
    name: "Tomas Rosicky",
    pos: "MCO",
    nat: "Czech Republic",
    club: "Legend",
    overall: 86,
  },
  {
    name: "Wlodzimierz Smolarek",
    pos: "DC",
    nat: "Poland",
    club: "Legend",
    overall: 86,
  },
  {
    name: "Cha Bum Kun",
    pos: "DC",
    nat: "South Korea",
    club: "Legend",
    overall: 86,
  },
  {
    name: "Peter Crouch",
    pos: "DC",
    nat: "England",
    club: "Legend",
    overall: 85,
  },
  {
    name: "Tim Howard",
    pos: "POR",
    nat: "United States",
    club: "Legend",
    overall: 85,
  },
];

const uniquePlayers = (arrays) => {
  const seen = new Set();

  return arrays.flat().filter((player) => {
    if (seen.has(player.name)) return false;
    seen.add(player.name);
    return true;
  });
};

exports.MARKET_POOL = uniquePlayers([
  exports.GLOBAL_POOL,
  exports.DRAFT_STARS,
  exports.SQUAD_POOL,
]);
