export const DRAFT_STARS = [
  {
    name: "Bruno Guimarães",
    pos: "MC",
    nat: "Brazil",
    club: "Newcastle United",
    overall: 86,
    pace: 73,
    shooting: 73,
    passing: 84,
    dribbling: 81,
    defending: 84,
    physical: 80,
  },
  {
    name: "Cole Palmer",
    pos: "MCO",
    nat: "England",
    club: "Chelsea",
    overall: 86,
    pace: 80,
    shooting: 83,
    passing: 82,
    dribbling: 88,
    defending: 42,
    physical: 68,
  },
  {
    name: "Nico Schlotterbeck",
    pos: "DFC",
    nat: "Germany",
    club: "Borussia Dortmund",
    overall: 86,
    pace: 81,
    shooting: 43,
    passing: 72,
    dribbling: 65,
    defending: 84,
    physical: 83,
  },
  {
    name: "Martin Ødegaard",
    pos: "MCO",
    nat: "Norway",
    club: "Arsenal",
    overall: 86,
    pace: 73,
    shooting: 80,
    passing: 88,
    dribbling: 88,
    defending: 60,
    physical: 64,
  },
  {
    name: "Scott McTominay",
    pos: "MC",
    nat: "Scotland",
    club: "Napoli",
    overall: 86,
    pace: 81,
    shooting: 43,
    passing: 72,
    dribbling: 65,
    defending: 84,
    physical: 83,
  },
  {
    name: "Dayot Upamecano",
    pos: "DFC",
    nat: "France",
    club: "Bayern Munich",
    overall: 86,
    pace: 81,
    shooting: 44,
    passing: 70,
    dribbling: 63,
    defending: 85,
    physical: 86,
  },
  {
    name: "Bremer",
    pos: "DFC",
    nat: "Brazil",
    club: "Juventus",
    overall: 86,
    pace: 81,
    shooting: 43,
    passing: 72,
    dribbling: 65,
    defending: 84,
    physical: 83,
  },
  {
    name: "Viktor Gyökeres",
    pos: "DC",
    nat: "Sweden",
    club: "Arsenal",
    overall: 86,
    pace: 84,
    shooting: 88,
    passing: 70,
    dribbling: 82,
    defending: 35,
    physical: 86,
  },
  {
    name: "Ryan Gravenberch",
    pos: "MCD",
    nat: "Netherlands",
    club: "Liverpool",
    overall: 86,
    pace: 81,
    shooting: 70,
    passing: 80,
    dribbling: 84,
    defending: 78,
    physical: 78,
  },
  {
    name: "Dominik Szoboszlai",
    pos: "MCO",
    nat: "Hungary",
    club: "Liverpool",
    overall: 86,
    pace: 80,
    shooting: 81,
    passing: 85,
    dribbling: 84,
    defending: 62,
    physical: 78,
  },
  {
    name: "Victor Osimhen",
    pos: "DC",
    nat: "Nigeria",
    club: "Galatasaray",
    overall: 86,
    pace: 90,
    shooting: 86,
    passing: 65,
    dribbling: 82,
    defending: 25,
    physical: 85,
  },
  {
    name: "Federico Dimarco",
    pos: "LI",
    nat: "Italy",
    club: "Inter Milan",
    overall: 86,
    pace: 78,
    shooting: 74,
    passing: 84,
    dribbling: 80,
    defending: 80,
    physical: 75,
  },
  {
    name: "Hakan Çalhanoğlu",
    pos: "MCD",
    nat: "Turkey",
    club: "Inter Milan",
    overall: 86,
    pace: 65,
    shooting: 82,
    passing: 88,
    dribbling: 85,
    defending: 65,
    physical: 75,
  },
  {
    name: "Désiré Doué",
    pos: "ED",
    nat: "France",
    club: "PSG",
    overall: 86,
    pace: 84,
    shooting: 80,
    passing: 78,
    dribbling: 89,
    defending: 52,
    physical: 76,
  },
  {
    name: "Lionel Messi",
    pos: "MCO",
    nat: "Argentina",
    club: "Inter Miami",
    overall: 86,
    pace: 77,
    shooting: 85,
    passing: 86,
    dribbling: 89,
    defending: 34,
    physical: 66,
  },
  {
    name: "Jules Koundé",
    pos: "LD",
    nat: "France",
    club: "Barcelona",
    overall: 86,
    pace: 84,
    shooting: 55,
    passing: 74,
    dribbling: 78,
    defending: 83,
    physical: 85,
  },
  {
    name: "Robert Lewandowski",
    pos: "DC",
    nat: "Poland",
    club: "Barcelona",
    overall: 86,
    pace: 71,
    shooting: 88,
    passing: 78,
    dribbling: 83,
    defending: 48,
    physical: 83,
  },
  {
    name: "Julián Álvarez",
    pos: "DC",
    nat: "Argentina",
    club: "Atletico de Madrid",
    overall: 86,
    pace: 86,
    shooting: 86,
    passing: 83,
    dribbling: 87,
    defending: 63,
    physical: 82,
  },
];
