export const GLOBAL_POOL = [
  {
    name: "Gregor Kobel",
    pos: "POR",
    nat: "Switzerland",
    club: "Borussia Dortmund",
    overall: 86,
    pace: 46,
    shooting: 16,
    passing: 72,
    dribbling: 40,
    defending: 13,
    physical: 78,
  },
  {
    name: "Joan García",
    pos: "POR",
    nat: "Spain",
    club: "Barcelona",
    overall: 86,
    pace: 52,
    shooting: 18,
    passing: 74,
    dribbling: 44,
    defending: 14,
    physical: 72,
  },
  {
    name: "Yann Sommer",
    pos: "POR",
    nat: "Switzerland",
    club: "Inter Milan",
    overall: 86,
    pace: 48,
    shooting: 18,
    passing: 72,
    dribbling: 42,
    defending: 13,
    physical: 76,
  },
  {
    name: "Mohamed Salah",
    pos: "ED",
    nat: "Egypt",
    club: "Liverpool",
    overall: 89,
    pace: 91,
    shooting: 89,
    passing: 81,
    dribbling: 89,
    defending: 45,
    physical: 75,
  },
  {
    name: "Kylian Mbappé",
    pos: "DC",
    nat: "France",
    club: "Real Madrid",
    overall: 91,
    pace: 97,
    shooting: 90,
    passing: 80,
    dribbling: 92,
    defending: 36,
    physical: 78,
  },
  {
    name: "Ousmane Dembélé",
    pos: "ED",
    nat: "France",
    club: "PSG",
    overall: 90,
    pace: 90,
    shooting: 85,
    passing: 82,
    dribbling: 93,
    defending: 30,
    physical: 74,
  },
  {
    name: "Jan Oblak",
    pos: "POR",
    nat: "Slovenia",
    club: "Atletico de Madrid",
    overall: 88,
    pace: 90,
    shooting: 85,
    passing: 82,
    dribbling: 93,
    defending: 30,
    physical: 74,
  },
  {
    name: "Rodri",
    pos: "MCD",
    nat: "Spain",
    club: "Manchester City",
    overall: 89,
    pace: 63,
    shooting: 74,
    passing: 88,
    dribbling: 84,
    defending: 89,
    physical: 84,
  },
  {
    name: "Virgil van Dijk",
    pos: "DFC",
    nat: "Netherlands",
    club: "Liverpool",
    overall: 88,
    pace: 78,
    shooting: 60,
    passing: 78,
    dribbling: 72,
    defending: 91,
    physical: 88,
  },
  {
    name: "Kevin de Bruyne",
    pos: "MC",
    nat: "Belgium",
    club: "Napoli",
    overall: 87,
    pace: 78,
    shooting: 60,
    passing: 78,
    dribbling: 72,
    defending: 91,
    physical: 88,
  },
  {
    name: "Jude Bellingham",
    pos: "MCO",
    nat: "England",
    club: "Real Madrid",
    overall: 89,
    pace: 80,
    shooting: 87,
    passing: 83,
    dribbling: 88,
    defending: 78,
    physical: 83,
  },
  {
    name: "Thibaut Courtois",
    pos: "POR",
    nat: "Belgium",
    club: "Real Madrid",
    overall: 90,
    pace: 80,
    shooting: 87,
    passing: 83,
    dribbling: 88,
    defending: 78,
    physical: 83,
  },
  {
    name: "Erling Haaland",
    pos: "DC",
    nat: "Norway",
    club: "Manchester City",
    overall: 91,
    pace: 88,
    shooting: 93,
    passing: 66,
    dribbling: 81,
    defending: 29,
    physical: 89,
  },
  {
    name: "Raphinha",
    pos: "EI",
    nat: "Brazil",
    club: "Barcelona",
    overall: 89,
    pace: 90,
    shooting: 84,
    passing: 83,
    dribbling: 88,
    defending: 42,
    physical: 70,
  },
  {
    name: "Lamine Yamal",
    pos: "ED",
    nat: "Spain",
    club: "Barcelona",
    overall: 89,
    pace: 88,
    shooting: 82,
    passing: 85,
    dribbling: 91,
    defending: 32,
    physical: 62,
  },
  {
    name: "Achraf Hakimi",
    pos: "LD",
    nat: "Morocco",
    club: "PSG",
    overall: 89,
    pace: 92,
    shooting: 75,
    passing: 80,
    dribbling: 85,
    defending: 79,
    physical: 77,
  },
  {
    name: "Vitinha",
    pos: "MC",
    nat: "Portugal",
    club: "PSG",
    overall: 90,
    pace: 78,
    shooting: 78,
    passing: 88,
    dribbling: 90,
    defending: 74,
    physical: 70,
  },
  {
    name: "Nicolò Barella",
    pos: "MC",
    nat: "Italy",
    club: "Inter Milan",
    overall: 88,
    pace: 78,
    shooting: 78,
    passing: 84,
    dribbling: 85,
    defending: 78,
    physical: 80,
  },
  {
    name: "Gianluigi Donnarumma",
    pos: "POR",
    nat: "Italy",
    club: "Manchester City",
    overall: 89,
    pace: 50,
    shooting: 20,
    passing: 75,
    dribbling: 42,
    defending: 14,
    physical: 82,
  },
  {
    name: "Joshua Kimmich",
    pos: "MCD",
    nat: "Germany",
    club: "Bayern Munich",
    overall: 89,
    pace: 70,
    shooting: 77,
    passing: 89,
    dribbling: 84,
    defending: 86,
    physical: 75,
  },
  {
    name: "Alisson",
    pos: "POR",
    nat: "Brazil",
    club: "Liverpool",
    overall: 88,
    pace: 48,
    shooting: 20,
    passing: 79,
    dribbling: 43,
    defending: 15,
    physical: 66,
  },
  {
    name: "Harry Kane",
    pos: "DC",
    nat: "England",
    club: "Bayern Munich",
    overall: 90,
    pace: 71,
    shooting: 91,
    passing: 84,
    dribbling: 84,
    defending: 46,
    physical: 84,
  },
  {
    name: "Fede Valverde",
    pos: "MC",
    nat: "Uruguay",
    club: "Real Madrid",
    overall: 89,
    pace: 88,
    shooting: 84,
    passing: 84,
    dribbling: 85,
    defending: 79,
    physical: 86,
  },
  {
    name: "Vinícius Júnior",
    pos: "EI",
    nat: "Brazil",
    club: "Real Madrid",
    overall: 89,
    pace: 95,
    shooting: 84,
    passing: 81,
    dribbling: 91,
    defending: 29,
    physical: 69,
  },
  {
    name: "Florian Wirtz",
    pos: "MCO",
    nat: "Germany",
    club: "Liverpool",
    overall: 87,
    pace: 81,
    shooting: 81,
    passing: 87,
    dribbling: 90,
    defending: 51,
    physical: 69,
  },
  {
    name: "Bukayo Saka",
    pos: "ED",
    nat: "England",
    club: "Arsenal",
    overall: 87,
    pace: 87,
    shooting: 84,
    passing: 83,
    dribbling: 87,
    defending: 48,
    physical: 73,
  },
  {
    name: "Gabriel Magalhães",
    pos: "DFC",
    nat: "Brazil",
    club: "Arsenal",
    overall: 89,
    pace: 75,
    shooting: 55,
    passing: 68,
    dribbling: 62,
    defending: 88,
    physical: 87,
  },
  {
    name: "Alexander Isak",
    pos: "DC",
    nat: "Sweden",
    club: "Liverpool",
    overall: 87,
    pace: 88,
    shooting: 87,
    passing: 74,
    dribbling: 85,
    defending: 32,
    physical: 78,
  },
  {
    name: "Jamal Musiala",
    pos: "MCO",
    nat: "Germany",
    club: "Bayern Munich",
    overall: 87,
    pace: 80,
    shooting: 82,
    passing: 80,
    dribbling: 90,
    defending: 66,
    physical: 65,
  },
  {
    name: "Michael Olise",
    pos: "ED",
    nat: "France",
    club: "Bayern Munich",
    overall: 89,
    pace: 87,
    shooting: 82,
    passing: 83,
    dribbling: 89,
    defending: 35,
    physical: 68,
  },
  {
    name: "João Neves",
    pos: "MC",
    nat: "Portugal",
    club: "PSG",
    overall: 88,
    pace: 78,
    shooting: 74,
    passing: 83,
    dribbling: 86,
    defending: 80,
    physical: 73,
  },
  {
    name: "Nuno Mendes",
    pos: "LI",
    nat: "Portugal",
    club: "PSG",
    overall: 88,
    pace: 90,
    shooting: 65,
    passing: 78,
    dribbling: 84,
    defending: 82,
    physical: 75,
  },
  {
    name: "Bruno Fernandes",
    pos: "MCO",
    nat: "Portugal",
    club: "Manchester United",
    overall: 88,
    pace: 73,
    shooting: 84,
    passing: 88,
    dribbling: 85,
    defending: 65,
    physical: 74,
  },
  {
    name: "Declan Rice",
    pos: "MCD",
    nat: "England",
    club: "Arsenal",
    overall: 88,
    pace: 76,
    shooting: 72,
    passing: 81,
    dribbling: 81,
    defending: 85,
    physical: 84,
  },
  {
    name: "Lautaro Martínez",
    pos: "DC",
    nat: "Argentina",
    club: "Inter",
    overall: 88,
    pace: 84,
    shooting: 88,
    passing: 80,
    dribbling: 85,
    defending: 60,
    physical: 64,
  },
  {
    name: "Willian Pacho",
    pos: "DFC",
    nat: "Ecuador",
    club: "PSG",
    overall: 88,
    pace: 80,
    shooting: 70,
    passing: 81,
    dribbling: 82,
    defending: 86,
    physical: 81,
  },
  {
    name: "Moisés Caicedo",
    pos: "MCD",
    nat: "Ecuador",
    club: "Chelsea",
    overall: 88,
    pace: 80,
    shooting: 70,
    passing: 81,
    dribbling: 82,
    defending: 86,
    physical: 81,
  },
  {
    name: "William Saliba",
    pos: "DFC",
    nat: "France",
    club: "Arsenal",
    overall: 88,
    pace: 82,
    shooting: 48,
    passing: 70,
    dribbling: 62,
    defending: 87,
    physical: 84,
  },
  {
    name: "Alessandro Bastoni",
    pos: "DFC",
    nat: "Italy",
    club: "Inter Milan",
    overall: 87,
    pace: 74,
    shooting: 48,
    passing: 80,
    dribbling: 70,
    defending: 86,
    physical: 80,
  },
  {
    name: "Rúben Dias",
    pos: "DFC",
    nat: "Portugal",
    club: "Manchester City",
    overall: 87,
    pace: 73,
    shooting: 45,
    passing: 74,
    dribbling: 60,
    defending: 90,
    physical: 86,
  },
  {
    name: "Khvicha Kvaratskhelia",
    pos: "EI",
    nat: "Georgia",
    club: "PSG",
    overall: 88,
    pace: 86,
    shooting: 84,
    passing: 85,
    dribbling: 89,
    defending: 68,
    physical: 70,
  },
  {
    name: "Alexis Mac Allister",
    pos: "MC",
    nat: "Argentina",
    club: "Liverpool",
    overall: 85,
    pace: 72,
    shooting: 78,
    passing: 85,
    dribbling: 86,
    defending: 68,
    physical: 70,
  },
  {
    name: "David Raya",
    pos: "POR",
    nat: "Spain",
    club: "Arsenal",
    overall: 87,
    pace: 50,
    shooting: 18,
    passing: 80,
    dribbling: 46,
    defending: 14,
    physical: 70,
  },
  {
    name: "Serhou Guirassy",
    pos: "DC",
    nat: "Guinea",
    club: "Borussia Dortmund",
    overall: 85,
    pace: 80,
    shooting: 86,
    passing: 64,
    dribbling: 78,
    defending: 30,
    physical: 82,
  },
  {
    name: "Marquinhos",
    pos: "DFC",
    nat: "Brazil",
    club: "PSG",
    overall: 87,
    pace: 72,
    shooting: 50,
    passing: 76,
    dribbling: 68,
    defending: 88,
    physical: 80,
  },
  {
    name: "Jonathan Tah",
    pos: "DFC",
    nat: "Germany",
    club: "Bayern Munich",
    overall: 87,
    pace: 74,
    shooting: 42,
    passing: 70,
    dribbling: 64,
    defending: 88,
    physical: 87,
  },
  {
    name: "Trent Alexander-Arnold",
    pos: "LD",
    nat: "England",
    club: "Real Madrid",
    overall: 85,
    pace: 76,
    shooting: 74,
    passing: 90,
    dribbling: 82,
    defending: 72,
    physical: 68,
  },
  {
    name: "Luis Díaz",
    pos: "EI",
    nat: "Colombia",
    club: "Bayern Munich",
    overall: 87,
    pace: 90,
    shooting: 80,
    passing: 75,
    dribbling: 87,
    defending: 38,
    physical: 72,
  },
  {
    name: "Patrik Schick",
    pos: "DC",
    nat: "Czech Republic",
    club: "Bayer Leverkusen",
    overall: 85,
    pace: 78,
    shooting: 84,
    passing: 70,
    dribbling: 79,
    defending: 30,
    physical: 84,
  },
  {
    name: "Ibrahima Konaté",
    pos: "DFC",
    nat: "France",
    club: "Liverpool",
    overall: 84,
    pace: 84,
    shooting: 42,
    passing: 65,
    dribbling: 58,
    defending: 87,
    physical: 88,
  },
  {
    name: "Lukaku",
    pos: "DC",
    nat: "Belgium",
    club: "Napoli",
    overall: 83,
    pace: 84,
    shooting: 86,
    passing: 82,
    dribbling: 88,
    defending: 47,
    physical: 86,
  },
  {
    name: "Theo Hernández",
    pos: "LI",
    nat: "France",
    club: "Al Hilal",
    overall: 84,
    pace: 90,
    shooting: 72,
    passing: 74,
    dribbling: 80,
    defending: 78,
    physical: 80,
  },
  {
    name: "Péter Gulácsi",
    pos: "POR",
    nat: "Hungary",
    club: "RB Leipzig",
    overall: 84,
    pace: 42,
    shooting: 15,
    passing: 70,
    dribbling: 38,
    defending: 12,
    physical: 68,
  },
  {
    name: "Bryan Mbeumo",
    pos: "DC",
    nat: "Cameroon",
    club: "Manchester United",
    overall: 85,
    pace: 84,
    shooting: 84,
    passing: 76,
    dribbling: 83,
    defending: 38,
    physical: 74,
  },
  {
    name: "Unai Simón",
    pos: "POR",
    nat: "Spain",
    club: "Athletic Club",
    overall: 84,
    pace: 42,
    shooting: 14,
    passing: 72,
    dribbling: 40,
    defending: 11,
    physical: 74,
  },
  {
    name: "Diogo Costa",
    pos: "POR",
    nat: "Portugal",
    club: "Porto",
    overall: 84,
    pace: 44,
    shooting: 14,
    passing: 70,
    dribbling: 38,
    defending: 11,
    physical: 72,
  },
  {
    name: "Jordan Pickford",
    pos: "POR",
    nat: "England",
    club: "Everton",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Emiliano Martínez",
    pos: "POR",
    nat: "Argentina",
    club: "Aston Villa",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Karim Benzema",
    pos: "DC",
    nat: "France",
    club: "Al Hilal",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Cristiano Ronaldo",
    pos: "DC",
    nat: "Portugal",
    club: "Al Nassr",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Bradley Barcola",
    pos: "EI",
    nat: "France",
    club: "PSG",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Morgan Rogers",
    pos: "MCO",
    nat: "England",
    club: "Aston Villa",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Rayan Cherki",
    pos: "ED",
    nat: "France",
    club: "Manchester City",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Rodrygo",
    pos: "ED",
    nat: "Brazil",
    club: "Real Madrid",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Antoine Semenyo",
    pos: "ED",
    nat: "Ghana",
    club: "Manchester City",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Eder Militao",
    pos: "DFC",
    nat: "Brazil",
    club: "Real Madrid",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Eberechi Eze",
    pos: "MCO",
    nat: "England",
    club: "Arsenal",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Denzel Dumfries",
    pos: "LD",
    nat: "Netherlands",
    club: "Inter Milan",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Ngolo Kanté",
    pos: "MCD",
    nat: "France",
    club: "Fenerbahçe",
    overall: 84,
    pace: 62,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Joao Cancelo",
    pos: "LD",
    nat: "Portugal",
    club: "Barcelona",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Antonio Rudiger",
    pos: "DFC",
    nat: "Germany",
    club: "Real Madrid",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Dani Carvajal",
    pos: "LD",
    nat: "Spain",
    club: "Real Madrid",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Son Heung-Min",
    pos: "EI",
    nat: "South Korea",
    club: "LA FC",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Riyad Mahrez",
    pos: "ED",
    nat: "Algeria",
    club: "Al Ahli",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Isco",
    pos: "MCO",
    nat: "Spain",
    club: "Real Betis",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Antoine Griezmann",
    pos: "DC",
    nat: "France",
    club: "Atletico de Madrid",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "David de Gea",
    pos: "POR",
    nat: "Spain",
    club: "Fiorentina",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Marc André ter Stegen",
    pos: "POR",
    nat: "Germany",
    club: "Girona",
    overall: 84,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Pau Cubarsí",
    pos: "DFC",
    nat: "Spain",
    club: "Barcelona",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Arda Güler",
    pos: "MCO",
    nat: "Turkey",
    club: "Real Madrid",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Warren Zaïre-Emery",
    pos: "MC",
    nat: "France",
    club: "PSG",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Gavi",
    pos: "MC",
    nat: "Spain",
    club: "Barcelona",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Alejandro Balde",
    pos: "LI",
    nat: "Spain",
    club: "Barcelona",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Omar Marmoush",
    pos: "DC",
    nat: "Egypt",
    club: "Manchester City",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Piero Hincapié",
    pos: "LI",
    nat: "Ecuador",
    club: "Arsenal",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Giorgi Mamardashvili",
    pos: "POR",
    nat: "Georgia",
    club: "Liverpool",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Jeremy Doku",
    pos: "EI",
    nat: "Belgium",
    club: "Manchester City",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Mason Greenwood",
    pos: "ED",
    nat: "England",
    club: "Olympique Marseille",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Moussa Diaby",
    pos: "ED",
    nat: "France",
    club: "Al Ittihad",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Cody Gakpo",
    pos: "EI",
    nat: "Netherlands",
    club: "Liverpool",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "David Raum",
    pos: "LI",
    nat: "Germany",
    club: "RB Leipzig",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Ademola Lookman",
    pos: "EI",
    nat: "Nigeria",
    club: "Atletico de Madrid",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Manuel Akanji",
    pos: "DFC",
    nat: "Switzerland",
    club: "Inter Milan",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "André-Franck Zambo Anguissa",
    pos: "MC",
    nat: "Cameroon",
    club: "Napoli",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Bernardo Silva",
    pos: "MC",
    nat: "Portugal",
    club: "Manchester City",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Giovanni Di Lorenzo",
    pos: "LD",
    nat: "Italy",
    club: "Napoli",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Sadio Mané",
    pos: "EI",
    nat: "Senegal",
    club: "Al Nassr",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Neymar Jr.",
    pos: "MCO",
    nat: "Brazil",
    club: "Free Agent",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Fermín",
    pos: "MCO",
    nat: "Spain",
    club: "Barcelona",
    overall: 83,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Mike Maignan",
    pos: "POR",
    nat: "France",
    club: "AC Milan",
    overall: 87,
    pace: 52,
    shooting: 18,
    passing: 78,
    dribbling: 46,
    defending: 14,
    physical: 80,
  },
  {
    name: "Rafael Leão",
    pos: "DC",
    nat: "Portugal",
    club: "AC Milan",
    overall: 84,
    pace: 93,
    shooting: 80,
    passing: 75,
    dribbling: 88,
    defending: 30,
    physical: 78,
  },
  {
    name: "Luka Modrić",
    pos: "MCD",
    nat: "Croatia",
    club: "AC Milan",
    overall: 85,
    pace: 62,
    shooting: 76,
    passing: 89,
    dribbling: 87,
    defending: 60,
    physical: 60,
  },
  {
    name: "Matheus Cunha",
    pos: "EI",
    nat: "Brazil",
    club: "Manchester United",
    overall: 83,
    pace: 82,
    shooting: 80,
    passing: 76,
    dribbling: 84,
    defending: 40,
    physical: 78,
  },
  {
    name: "Adrien Rabiot",
    pos: "MC",
    nat: "France",
    club: "AC Milan",
    overall: 85,
    pace: 72,
    shooting: 78,
    passing: 82,
    dribbling: 80,
    defending: 74,
    physical: 84,
  },
  {
    name: "Granit Xhaka",
    pos: "MCD",
    nat: "Switzerland",
    club: "Sunderland",
    overall: 85,
    pace: 62,
    shooting: 74,
    passing: 84,
    dribbling: 78,
    defending: 82,
    physical: 78,
  },
  {
    name: "James Maddison",
    pos: "MCO",
    nat: "England",
    club: "Tottenham",
    overall: 83,
    pace: 70,
    shooting: 80,
    passing: 86,
    dribbling: 88,
    defending: 42,
    physical: 62,
  },
  {
    name: "Pedri",
    pos: "MC",
    nat: "Spain",
    club: "Barcelona",
    overall: 90,
    pace: 75,
    shooting: 78,
    passing: 88,
    dribbling: 90,
    defending: 78,
    physical: 65,
  },
  {
    name: "Martín Zubimendi",
    pos: "MCD",
    nat: "Spain",
    club: "Arsenal",
    overall: 85,
    pace: 68,
    shooting: 72,
    passing: 85,
    dribbling: 82,
    defending: 84,
    physical: 72,
  },
  {
    name: "Enzo Fernández",
    pos: "MC",
    nat: "Argentina",
    club: "Chelsea",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Sandro Tonali",
    pos: "MCD",
    nat: "Italy",
    club: "Newcastle United",
    overall: 85,
    pace: 68,
    shooting: 75,
    passing: 84,
    dribbling: 82,
    defending: 80,
    physical: 78,
  },
  {
    name: "Tijjani Reijnders",
    pos: "MC",
    nat: "Netherlands",
    club: "Manchester City",
    overall: 85,
    pace: 79,
    shooting: 78,
    passing: 84,
    dribbling: 86,
    defending: 68,
    physical: 70,
  },
  {
    name: "Fabián Ruiz",
    pos: "MC",
    nat: "Spain",
    club: "PSG",
    overall: 85,
    pace: 68,
    shooting: 80,
    passing: 86,
    dribbling: 85,
    defending: 70,
    physical: 70,
  },
  {
    name: "Marcos Llorente",
    pos: "LD",
    nat: "Spain",
    club: "Atletico de Madrid",
    overall: 85,
    pace: 90,
    shooting: 78,
    passing: 78,
    dribbling: 82,
    defending: 75,
    physical: 82,
  },
  {
    name: "Nico Williams",
    pos: "EI",
    nat: "Spain",
    club: "Athletic Club",
    overall: 85,
    pace: 93,
    shooting: 78,
    passing: 78,
    dribbling: 88,
    defending: 30,
    physical: 65,
  },
  {
    name: "Dani Olmo",
    pos: "MCO",
    nat: "Spain",
    club: "Barcelona",
    overall: 84,
    pace: 78,
    shooting: 80,
    passing: 84,
    dribbling: 87,
    defending: 50,
    physical: 65,
  },
  {
    name: "Ferran Torres",
    pos: "DC",
    nat: "Spain",
    club: "Barcelona",
    overall: 84,
    pace: 84,
    shooting: 82,
    passing: 76,
    dribbling: 84,
    defending: 35,
    physical: 68,
  },
  {
    name: "Marc Cucurella",
    pos: "LI",
    nat: "Spain",
    club: "Chelsea",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Phil Foden",
    pos: "MCO",
    nat: "England",
    club: "Manchester City",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Marcus Thuram",
    pos: "DC",
    nat: "France",
    club: "Inter Milan",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Christian Pulisic",
    pos: "ED",
    nat: "United States",
    club: "AC Milan",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Ruben Neves",
    pos: "MCD",
    nat: "Portugal",
    club: "Al Hilal",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Sergej Milinković-Savić",
    pos: "MC",
    nat: "Serbia",
    club: "Al Hilal",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Youri Tielemans",
    pos: "MC",
    nat: "Belgium",
    club: "Aston Villa",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Gavi",
    pos: "MC",
    nat: "Spain",
    club: "Barcelona",
    overall: 83,
    pace: 78,
    shooting: 72,
    passing: 80,
    dribbling: 84,
    defending: 72,
    physical: 70,
  },
  {
    name: "Mikel Merino",
    pos: "MC",
    nat: "Spain",
    club: "Arsenal",
    overall: 83,
    pace: 72,
    shooting: 76,
    passing: 80,
    dribbling: 80,
    defending: 75,
    physical: 80,
  },
  {
    name: "Alphonso Davies",
    pos: "LI",
    nat: "Canada",
    club: "Bayern Munich",
    overall: 83,
    pace: 94,
    shooting: 66,
    passing: 80,
    dribbling: 85,
    defending: 82,
    physical: 82,
  },
  {
    name: "Exequiel Palacios",
    pos: "MC",
    nat: "Argentina",
    club: "Bayer Leverkusen",
    overall: 83,
    pace: 75,
    shooting: 78,
    passing: 83,
    dribbling: 82,
    defending: 72,
    physical: 74,
  },
  {
    name: "Willi Orbán",
    pos: "DFC",
    nat: "Hungary",
    club: "RB Leipzig",
    overall: 83,
    pace: 70,
    shooting: 40,
    passing: 65,
    dribbling: 55,
    defending: 84,
    physical: 85,
  },
  {
    name: "Alejandro Grimaldo",
    pos: "LI",
    nat: "Spain",
    club: "Bayer Leverkusen",
    overall: 85,
    pace: 78,
    shooting: 78,
    passing: 84,
    dribbling: 85,
    defending: 74,
    physical: 72,
  },
  {
    name: "Marco Carnesecchi",
    pos: "POR",
    nat: "Italy",
    club: "Atalanta",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Josko Gvardiol",
    pos: "DFC",
    nat: "Croatia",
    club: "Manchester City",
    overall: 85,
    pace: 88,
    shooting: 79,
    passing: 76,
    dribbling: 84,
    defending: 32,
    physical: 70,
  },
  {
    name: "Angelo Stiller",
    pos: "MC",
    nat: "Germany",
    club: "Stuttgart",
    overall: 83,
    pace: 66,
    shooting: 74,
    passing: 85,
    dribbling: 80,
    defending: 72,
    physical: 68,
  },
  {
    name: "Oliver Baumann",
    pos: "POR",
    nat: "Germany",
    club: "TSG Hoffenheim",
    overall: 84,
    pace: 44,
    shooting: 14,
    passing: 68,
    dribbling: 36,
    defending: 11,
    physical: 66,
  },
  {
    name: "Aleix García",
    pos: "MC",
    nat: "Spain",
    club: "Bayer Leverkusen",
    overall: 84,
    pace: 68,
    shooting: 72,
    passing: 83,
    dribbling: 80,
    defending: 70,
    physical: 68,
  },
  {
    name: "Dybala",
    pos: "MCO",
    nat: "Argentina",
    club: "Roma",
    overall: 85,
    pace: 78,
    shooting: 84,
    passing: 82,
    dribbling: 88,
    defending: 36,
    physical: 65,
  },
  {
    name: "Maximilian Mittelstädt",
    pos: "LI",
    nat: "Germany",
    club: "Stuttgart",
    overall: 83,
    pace: 80,
    shooting: 60,
    passing: 76,
    dribbling: 78,
    defending: 74,
    physical: 70,
  },
  {
    name: "Felix Nmecha",
    pos: "MC",
    nat: "Germany",
    club: "Borussia Dortmund",
    overall: 84,
    pace: 75,
    shooting: 72,
    passing: 78,
    dribbling: 80,
    defending: 68,
    physical: 75,
  },
  {
    name: "Lobotka",
    pos: "MCD",
    nat: "Slovakia",
    club: "Napoli",
    overall: 83,
    pace: 65,
    shooting: 62,
    passing: 84,
    dribbling: 83,
    defending: 78,
    physical: 68,
  },
  {
    name: "Hugo Ekitike",
    pos: "DC",
    nat: "France",
    club: "Liverpool",
    overall: 85,
    pace: 90,
    shooting: 86,
    passing: 65,
    dribbling: 82,
    defending: 25,
    physical: 85,
  },
];
