export const LEGEND_POOL_2 = [
{
    name: "Miroslav Klose",
    pos: "DC",
    nat: "Germany",
    club: "Legend",
    overall: 88,
  },
{
    name: "Pavel Nedved",
    pos: "EI",
    nat: "Czech Republic",
    club: "Legend",
    overall: 88,
  },
{
    name: "Giorgio Chiellini",
    pos: "DFC",
    nat: "Italy",
    club: "Legend",
    overall: 88,
  },
{
    name: "Iván Zamorano",
    pos: "DC",
    nat: "Chile",
    club: "Legend",
    overall: 88,
  },
{
    name: "Jari Litmanen",
    pos: "MCO",
    nat: "Finland",
    club: "Legend",
    overall: 88,
  },
{
    name: "Diego Forlán",
    pos: "DC",
    nat: "Uruguay",
    club: "Legend",
    overall: 88,
  },
{
    name: "Rafa Márquez",
    pos: "DFC",
    nat: "Mexico",
    club: "Legend",
    overall: 88,
  },
{
    name: "Paolo Futre",
    pos: "EI",
    nat: "Portugal",
    club: "Legend",
    overall: 88,
  },
{
    name: "Wesley Sneijder",
    pos: "MCO",
    nat: "Netherlands",
    club: "Legend",
    overall: 88,
  },
{
    name: "Antonio Di Natale",
    pos: "DC",
    nat: "Italy",
    club: "Legend",
    overall: 88,
  },
{
    name: "Marek Hamsík",
    pos: "MCO",
    nat: "Slovakia",
    club: "Legend",
    overall: 87,
  },
{
    name: "Rui Costa",
    pos: "MCO",
    nat: "Portugal",
    club: "Legend",
    overall: 87,
  },
{
    name: "Zé Roberto",
    pos: "EI",
    nat: "Brazil",
    club: "Legend",
    overall: 87,
  },
{
    name: "Daniele De Rossi",
    pos: "MCD",
    nat: "Italy",
    club: "Legend",
    overall: 87,
  },
{
    name: "Claudio Marchisio",
    pos: "MC",
    nat: "Italy",
    club: "Legend",
    overall: 87,
  },
{
    name: "Xabi Alonso",
    pos: "MCD",
    nat: "Spain",
    club: "Legend",
    overall: 87,
  },
{
    name: "Jaap Stam",
    pos: "DFC",
    nat: "Netherlands",
    club: "Legend",
    overall: 87,
  },
{
    name: "Iván Córdoba",
    pos: "DFC",
    nat: "Colombia",
    club: "Legend",
    overall: 87,
  },
{
    name: "Fernando Torres",
    pos: "DC",
    nat: "Spain",
    club: "Legend",
    overall: 87,
  },
{
    name: "Dimitar Berbatov",
    pos: "DC",
    nat: "Bulgary",
    club: "Legend",
    overall: 87,
  },
{
    name: "Frank Lampard",
    pos: "MC",
    nat: "England",
    club: "Legend",
    overall: 87,
  },
{
    name: "Yaya Touré",
    pos: "MC",
    nat: "Ivory Coast",
    club: "Legend",
    overall: 87,
  },
{
    name: "Nemanja Vidic",
    pos: "DFC",
    nat: "Serbia",
    club: "Legend",
    overall: 87,
  },
{
    name: "Emmanuel Petit",
    pos: "MCD",
    nat: "France",
    club: "Legend",
    overall: 87,
  },
{
    name: "Steve McManaman",
    pos: "ED",
    nat: "England",
    club: "Legend",
    overall: 87,
  },
{
    name: "Ian Wright",
    pos: "DC",
    nat: "England",
    club: "Legend",
    overall: 87,
  },
{
    name: "Harry Kewell",
    pos: "EI",
    nat: "Australia",
    club: "Legend",
    overall: 87,
  },
{
    name: "Davor Suker",
    pos: "DC",
    nat: "Croatia",
    club: "Legend",
    overall: 87,
  },
{
    name: "Gianluca Zambrotta",
    pos: "LD",
    nat: "Italy",
    club: "Legend",
    overall: 86,
  },
{
    name: "Dirk Kuyt",
    pos: "MCO",
    nat: "Netherlands",
    club: "Legend",
    overall: 86,
  },
{
    name: "Jerzy Dudek",
    pos: "POR",
    nat: "Poland",
    club: "Legend",
    overall: 86,
  },
{
    name: "Landon Donovan",
    pos: "MCO",
    nat: "United States",
    club: "Legend",
    overall: 86,
  },
{
    name: "Ramires",
    pos: "MCD",
    nat: "Brazil",
    club: "Legend",
    overall: 86,
  },
{
    name: "John Arne Riise",
    pos: "LI",
    nat: "Norway",
    club: "Legend",
    overall: 86,
  },
{
    name: "Blaise Matuidi",
    pos: "MCD",
    nat: "France",
    club: "Legend",
    overall: 86,
  },
{
    name: "Joan Capdevila",
    pos: "LI",
    nat: "Spain",
    club: "Legend",
    overall: 86,
  },
{
    name: "Guti",
    pos: "MC",
    nat: "Spain",
    club: "Legend",
    overall: 86,
  },
{
    name: "Sidney Govou",
    pos: "DC",
    nat: "France",
    club: "Legend",
    overall: 86,
  },
{
    name: "Ludovic Giuly",
    pos: "ED",
    nat: "France",
    club: "Legend",
    overall: 86,
  },
{
    name: "Ole Gunnar Solskjaer",
    pos: "DC",
    nat: "Norway",
    club: "Legend",
    overall: 86,
  },
{
    name: "Park Ji Sung",
    pos: "EI",
    nat: "South Korea",
    club: "Legend",
    overall: 86,
  },
{
    name: "Tomas Rosicky",
    pos: "MCO",
    nat: "Czech Republic",
    club: "Legend",
    overall: 86,
  },
{
    name: "Wlodzimierz Smolarek",
    pos: "DC",
    nat: "Poland",
    club: "Legend",
    overall: 86,
  },
{
    name: "Cha Bum Kun",
    pos: "DC",
    nat: "South Korea",
    club: "Legend",
    overall: 86,
  },
{
    name: "Peter Crouch",
    pos: "DC",
    nat: "England",
    club: "Legend",
    overall: 85,
  },
{
    name: "Tim Howard",
    pos: "POR",
    nat: "United States",
    club: "Legend",
    overall: 85,
  }
];
