export const LEGEND_POOL_1 = [
{
    name: "Toni Kroos",
    pos: "MC",
    nat: "Germany",
    club: "Legend",
    overall: 90,
  },
{
    name: "Raúl",
    pos: "DC",
    nat: "Spain",
    club: "Legend",
    overall: 90,
  },
{
    name: "Iker Casillas",
    pos: "POR",
    nat: "Spain",
    club: "Legend",
    overall: 90,
  },
{
    name: "Rivaldo",
    pos: "EI",
    nat: "Brazil",
    club: "Legend",
    overall: 90,
  },
{
    name: "Andrea Pirlo",
    pos: "MC",
    nat: "Italy",
    club: "Legend",
    overall: 90,
  },
{
    name: "Dennis Bergkamp",
    pos: "DC",
    nat: "Netherlands",
    club: "Legend",
    overall: 90,
  },
{
    name: "Xavi",
    pos: "MC",
    nat: "Spain",
    club: "Legend",
    overall: 91,
  },
{
    name: "Oliver Kahn",
    pos: "POR",
    nat: "Germany",
    club: "Legend",
    overall: 91,
  },
{
    name: "Thierry Henry",
    pos: "DC",
    nat: "France",
    club: "Legend",
    overall: 91,
  },
{
    name: "Zlatan Ibrahimovic",
    pos: "DC",
    nat: "Sweden",
    club: "Legend",
    overall: 91,
  },
{
    name: "Ronaldo Nazario",
    pos: "DC",
    nat: "Brazil",
    club: "Legend",
    overall: 94,
  },
{
    name: "Zinedine Zidane",
    pos: "MCO",
    nat: "France",
    club: "Legend",
    overall: 93,
  },
{
    name: "Andrés Iniesta",
    pos: "MC",
    nat: "Spain",
    club: "Legend",
    overall: 92,
  },
{
    name: "Roberto Baggio",
    pos: "MCO",
    nat: "Italy",
    club: "Legend",
    overall: 91,
  },
{
    name: "Gianluca Vialli",
    pos: "DC",
    nat: "Italy",
    club: "Legend",
    overall: 89,
  },
{
    name: "Ruud van Nistelrooy",
    pos: "DC",
    nat: "Netherlands",
    club: "Legend",
    overall: 89,
  },
{
    name: "Lúcio",
    pos: "DFC",
    nat: "Brazil",
    club: "Legend",
    overall: 89,
  },
{
    name: "Didier Drogba",
    pos: "DC",
    nat: "Ivory Coast",
    club: "Legend",
    overall: 89,
  },
{
    name: "Philipp Lahm",
    pos: "LD",
    nat: "Germany",
    club: "Legend",
    overall: 89,
  },
{
    name: "Fernando Morientes",
    pos: "DC",
    nat: "Spain",
    club: "Legend",
    overall: 89,
  },
{
    name: "Carles Puyol",
    pos: "DFC",
    nat: "Spain",
    club: "Legend",
    overall: 89,
  },
{
    name: "Samuel Eto'o",
    pos: "DC",
    nat: "Cameroon",
    club: "Legend",
    overall: 89,
  },
{
    name: "Marcelo",
    pos: "LI",
    nat: "Brazil",
    club: "Legend",
    overall: 89,
  },
{
    name: "Hristo Stoichkov",
    pos: "DC",
    nat: "Bulgary",
    club: "Legend",
    overall: 89,
  },
{
    name: "Emilio Butragueño",
    pos: "DC",
    nat: "Spain",
    club: "Legend",
    overall: 89,
  },
{
    name: "Francesco Totti",
    pos: "DC",
    nat: "Italy",
    club: "Legend",
    overall: 89,
  },
{
    name: "Kaká",
    pos: "MCO",
    nat: "Brazil",
    club: "Legend",
    overall: 89,
  },
{
    name: "Alessandro Nesta",
    pos: "DFC",
    nat: "Italy",
    club: "Legend",
    overall: 89,
  },
{
    name: "Javier Zanetti",
    pos: "LD",
    nat: "Argentina",
    club: "Legend",
    overall: 89,
  },
{
    name: "Franck Ribéry",
    pos: "EI",
    nat: "France",
    club: "Legend",
    overall: 88,
  },
{
    name: "Maicon",
    pos: "LD",
    nat: "Brazil",
    club: "Legend",
    overall: 88,
  },
{
    name: "Ricardo Carvalho",
    pos: "DFC",
    nat: "Portugal",
    club: "Legend",
    overall: 88,
  },
{
    name: "Patrick Vieira",
    pos: "MC",
    nat: "France",
    club: "Legend",
    overall: 88,
  },
{
    name: "Diego Milito",
    pos: "DC",
    nat: "Argentina",
    club: "Legend",
    overall: 88,
  },
{
    name: "Bixente Lizarazu",
    pos: "LI",
    nat: "France",
    club: "Legend",
    overall: 88,
  },
{
    name: "Lilian Thuram",
    pos: "LD",
    nat: "France",
    club: "Legend",
    overall: 88,
  },
{
    name: "Petr Cech",
    pos: "POR",
    nat: "Czech Republic",
    club: "Legend",
    overall: 88,
  },
{
    name: "Jay-Jay Okocha",
    pos: "MCO",
    nat: "Nigeria",
    club: "Legend",
    overall: 88,
  },
{
    name: "Carlos Tévez",
    pos: "DC",
    nat: "Argentina",
    club: "Legend",
    overall: 88,
  },
{
    name: "Robin van Persie",
    pos: "DC",
    nat: "Netherlands",
    club: "Legend",
    overall: 88,
  },
{
    name: "Javier Mascherano",
    pos: "DFC",
    nat: "Argentina",
    club: "Legend",
    overall: 88,
  },
{
    name: "Gareth Bale",
    pos: "ED",
    nat: "Wales",
    club: "Legend",
    overall: 88,
  },
{
    name: "Bastian Schweinsteiger",
    pos: "MC",
    nat: "Germany",
    club: "Legend",
    overall: 88,
  },
{
    name: "Steven Gerrard",
    pos: "MC",
    nat: "England",
    club: "Legend",
    overall: 88,
  },
{
    name: "Rio Ferdinand",
    pos: "DFC",
    nat: "England",
    club: "Legend",
    overall: 88,
  },
{
    name: "Vincent Kompany",
    pos: "DFC",
    nat: "Belgium",
    club: "Legend",
    overall: 88,
  },
{
    name: "Mario Gómez",
    pos: "DC",
    nat: "Germany",
    club: "Legend",
    overall: 88,
  }
];
