export const SQUAD_POOL_1 = [
{ name: "Madueke", pos: "ED", nat: "England", club: "Arsenal", overall: 80 },
{
    name: "Murillo",
    pos: "DFC",
    nat: "Brazil",
    club: "Nottingham Forest",
    overall: 82,
  },
{
    name: "Robin Koch",
    pos: "DFC",
    nat: "Germany",
    club: "Eintracht Frankfurt",
    overall: 80,
  },
{
    name: "Nico O'Reilly",
    pos: "LI",
    nat: "England",
    club: "Manchester City",
    overall: 81,
  },
{
    name: "Álvaro Carreras",
    pos: "LI",
    nat: "Spain",
    club: "Real Madrid",
    overall: 81,
  },
{
    name: "Lewis Hall",
    pos: "LI",
    nat: "England",
    club: "Newcastle United",
    overall: 81,
  },
{
    name: "Miguel Gutiérrez",
    pos: "LI",
    nat: "Spain",
    club: "Napoli",
    overall: 81,
  },
{
    name: "Milos Kerkez",
    pos: "LI",
    nat: "Hungary",
    club: "Liverpool",
    overall: 81,
  },
{
    name: "Antonee Robinson",
    pos: "LI",
    nat: "United States",
    club: "Fulham",
    overall: 81,
  },
{
    name: "Lucas Hernández",
    pos: "LI",
    nat: "France",
    club: "PSG",
    overall: 81,
  },
{
    name: "Ferland Mendy",
    pos: "LI",
    nat: "France",
    club: "Real Madrid",
    overall: 81,
  },
{
    name: "Nathaniel Brown",
    pos: "LI",
    nat: "Germany",
    club: "Eintracht Frankfurt",
    overall: 80,
  },
{
    name: "Andrea Cambiaso",
    pos: "LI",
    nat: "Italy",
    club: "Juventus",
    overall: 80,
  },
{
    name: "Neco Williams",
    pos: "LI",
    nat: "Wales",
    club: "Nottingham Forest",
    overall: 80,
  },
{
    name: "Mattia Zacagni",
    pos: "EI",
    nat: "Italy",
    club: "Lazio",
    overall: 83,
  },
{
    name: "Rodrigo de Paul",
    pos: "MC",
    nat: "Argentina",
    club: "Inter Miami",
    overall: 83,
  },
{
    name: "Leandro Trossard",
    pos: "EI",
    nat: "Belgium",
    club: "Arsenal",
    overall: 83,
  },
{
    name: "Reinildo",
    pos: "LI",
    nat: "Mozambique",
    club: "Sunderland",
    overall: 80,
  },
{
    name: "Matthieu Udol",
    pos: "LI",
    nat: "France",
    club: "RC Lens",
    overall: 80,
  },
{
    name: "Leonardo Spinazzola",
    pos: "LI",
    nat: "Italy",
    club: "Napoli",
    overall: 80,
  },
{
    name: "Lucas Digne",
    pos: "LI",
    nat: "France",
    club: "Aston Villa",
    overall: 80,
  },
{
    name: "Jeremie Frimpong",
    pos: "LD",
    nat: "Netherlands",
    club: "Liverpool",
    overall: 82,
  },
{
    name: "Matheus Nunes",
    pos: "LD",
    nat: "Portugal",
    club: "Manchester City",
    overall: 82,
  },
{
    name: "Pedro Porro",
    pos: "LD",
    nat: "Spain",
    club: "Tottenham",
    overall: 82,
  },
{
    name: "Ollie Watkins",
    pos: "DC",
    nat: "England",
    club: "Aston Villa",
    overall: 82,
  },
{
    name: "Igor Thiago",
    pos: "DC",
    nat: "Brazil",
    club: "Brentford",
    overall: 82,
  },
{
    name: "Dusan Vlahovic",
    pos: "DC",
    nat: "Serbia",
    club: "Juventus",
    overall: 81,
  },
{
    name: "Jonathan David",
    pos: "DC",
    nat: "Canada",
    club: "Juventus",
    overall: 81,
  },
{
    name: "Yoane Wissa",
    pos: "DC",
    nat: "Republic of the Congo",
    club: "Newcastle United",
    overall: 81,
  },
{
    name: "Vedat Muriqi",
    pos: "DC",
    nat: "Kosovo",
    club: "Mallorca",
    overall: 81,
  },
{
    name: "Ayoze",
    pos: "DC",
    nat: "Spain",
    club: "Villarreal",
    overall: 81,
  },
{
    name: "Aubameyang",
    pos: "DC",
    nat: "Gabon",
    club: "Olympique Marseille",
    overall: 81,
  },
{
    name: "Gonçalo Ramos",
    pos: "DC",
    nat: "Portugal",
    club: "PSG",
    overall: 80,
  },
{
    name: "Nick Woltemade",
    pos: "DC",
    nat: "Germany",
    club: "Newcastle United",
    overall: 80,
  },
{
    name: "Luis Suárez",
    pos: "DC",
    nat: "Colombia",
    club: "Sporting CP",
    overall: 80,
  },
{
    name: "Youssef en-Nesyri",
    pos: "DC",
    nat: "Morocco",
    club: "Al Ittihad",
    overall: 80,
  },
{
    name: "Gabriel Jesus",
    pos: "DC",
    nat: "Brazil",
    club: "Arsenal",
    overall: 80,
  },
{
    name: "Daniel Muñoz",
    pos: "LD",
    nat: "Colombia",
    club: "Crystal Palace",
    overall: 82,
  },
{
    name: "Ben White",
    pos: "LD",
    nat: "England",
    club: "Arsenal",
    overall: 82,
  },
{
    name: "Matty Cash",
    pos: "LD",
    nat: "Poland",
    club: "Aston Villa",
    overall: 81,
  },
{
    name: "Michael Kayode",
    pos: "LD",
    nat: "Italy",
    club: "Brentford",
    overall: 80,
  },
{
    name: "Tino Livramento",
    pos: "LD",
    nat: "England",
    club: "Newcastle United",
    overall: 80,
  },
{
    name: "Óscar Mingueza",
    pos: "LD",
    nat: "Spain",
    club: "Celta",
    overall: 80,
  },
{
    name: "Andrei Ratiu",
    pos: "LD",
    nat: "Romania",
    club: "Rayo Vallecano",
    overall: 80,
  },
{
    name: "Noussair Mazraoui",
    pos: "LD",
    nat: "Morocco",
    club: "Manchester United",
    overall: 80,
  },
{
    name: "Julian Ryerson",
    pos: "LD",
    nat: "Norway",
    club: "Borussia Dortmund",
    overall: 80,
  },
{
    name: "Benjamin Henrichs",
    pos: "LD",
    nat: "Germany",
    club: "RB Leipzig",
    overall: 80,
  },
{
    name: "Ola Aina",
    pos: "LD",
    nat: "Nigeria",
    club: "Nottingham Forest",
    overall: 80,
  },
{
    name: "Aleksandar Pavlović",
    pos: "MCD",
    nat: "Germany",
    club: "Bayern Munich",
    overall: 82,
  },
{
    name: "Éderson",
    pos: "MC",
    nat: "Brazil",
    club: "Atalanta",
    overall: 82,
  },
{
    name: "Nico Paz",
    pos: "MCO",
    nat: "Argentina",
    club: "Como",
    overall: 82,
  },
{
    name: "Elliot Anderson",
    pos: "MCD",
    nat: "England",
    club: "Nottingham Forest",
    overall: 82,
  },
{
    name: "Carlos Augusto",
    pos: "LI",
    nat: "Brazil",
    club: "Inter Milan",
    overall: 81,
  },
{
    name: "Rayan Aït-Nouri",
    pos: "LI",
    nat: "Algeria",
    club: "Manchester City",
    overall: 81,
  },
{
    name: "Ritsu Doan",
    pos: "ED",
    nat: "Japan",
    club: "Eintracht Frankfurt",
    overall: 81,
  },
{
    name: "Jonathan Burkardt",
    pos: "DC",
    nat: "Germany",
    club: "Eintracht Frankfurt",
    overall: 82,
  },
{
    name: "Lukebakio",
    pos: "ED",
    nat: "Belgium",
    club: "Benfica",
    overall: 81,
  },
{
    name: "Vivian",
    pos: "DFC",
    nat: "Spain",
    club: "Athletic Club",
    overall: 82,
  },
{
    name: "Gonçalo Inácio",
    pos: "DFC",
    nat: "Portugal",
    club: "Sporting CP",
    overall: 81,
  },
{
    name: "Malick Thiaw",
    pos: "DFC",
    nat: "Germany",
    club: "Newcastle United",
    overall: 81,
  },
{
    name: "Ronald Araújo",
    pos: "DFC",
    nat: "Uruguay",
    club: "Barcelona",
    overall: 81,
  },
{
    name: "Sven Botman",
    pos: "DFC",
    nat: "Netherlands",
    club: "Newcastle United",
    overall: 81,
  },
{
    name: "Nayef Aguerd",
    pos: "DFC",
    nat: "Morocco",
    club: "Olympique Marseille",
    overall: 81,
  },
{
    name: "Maxence Lacroix",
    pos: "DFC",
    nat: "France",
    club: "Crystal Palace",
    overall: 81,
  },
{
    name: "Edmond Tapsoba",
    pos: "DFC",
    nat: "Burkina Faso",
    club: "Bayer Leverkusen",
    overall: 82,
  },
{
    name: "Ibañez",
    pos: "DFC",
    nat: "Brazil",
    club: "Al Ahli",
    overall: 82,
  },
{
    name: "Alessandro Buongiorno",
    pos: "DFC",
    nat: "Italy",
    club: "Napoli",
    overall: 82,
  },
{
    name: "Kim Min-Jae",
    pos: "DFC",
    nat: "South Korea",
    club: "Bayern Munich",
    overall: 82,
  },
{
    name: "Riccardo Calafiori",
    pos: "LI",
    nat: "Italy",
    club: "Arsenal",
    overall: 82,
  }
];
