export const SQUAD_POOL_2 = [
{
    name: "Gabriel Martinelli",
    pos: "EI",
    nat: "Brazil",
    club: "Arsenal",
    overall: 81,
  },
{
    name: "Lucas Chevalier",
    pos: "POR",
    nat: "France",
    club: "PSG",
    overall: 82,
  },
{
    name: "Matvey Safonov",
    pos: "POR",
    nat: "Russia",
    club: "PSG",
    overall: 82,
  },
{
    name: "Dean Henderson",
    pos: "POR",
    nat: "England",
    club: "Crystal Palace",
    overall: 82,
  },
{
    name: "Álex Remiro",
    pos: "POR",
    nat: "Spain",
    club: "Real Sociedad",
    overall: 82,
  },
{
    name: "Alex Meret",
    pos: "POR",
    nat: "Italy",
    club: "Napoli",
    overall: 82,
  },
{
    name: "Wladimiro Falcone",
    pos: "POR",
    nat: "Italy",
    club: "Lecce",
    overall: 82,
  },
{
    name: "Manuel Neuer",
    pos: "POR",
    nat: "Germany",
    club: "Bayern Munich",
    overall: 82,
  },
{
    name: "Guglielmo Vicario",
    pos: "POR",
    nat: "Italy",
    club: "Tottenham",
    overall: 81,
  },
{
    name: "Sam Lammens",
    pos: "POR",
    nat: "Belgium",
    club: "Manchester United",
    overall: 81,
  },
{
    name: "Michele di Gregorio",
    pos: "POR",
    nat: "Italy",
    club: "Juventus",
    overall: 81,
  },
{
    name: "Édouard Mendy",
    pos: "POR",
    nat: "Senegal",
    club: "Al Ahli",
    overall: 81,
  },
{
    name: "Koen Casteels",
    pos: "POR",
    nat: "Belgium",
    club: "Al Qadsiah",
    overall: 82,
  },
{
    name: "Jurriën Timber",
    pos: "LD",
    nat: "Netherlands",
    club: "Arsenal",
    overall: 82,
  },
{
    name: "Gabriel Jesus",
    pos: "DC",
    nat: "Brazil",
    club: "Arsenal",
    overall: 80,
  },
{
    name: "Matthijs de Ligt",
    pos: "DFC",
    nat: "Netherlands",
    club: "Manchester United",
    overall: 82,
  },
{
    name: "Lisandro Martínez",
    pos: "DFC",
    nat: "Argentina",
    club: "Manchester United",
    overall: 81,
  },
{
    name: "Antony",
    pos: "ED",
    nat: "Brazil",
    club: "Manchester United",
    overall: 81,
  },
{
    name: "Mohammed Kudus",
    pos: "ED",
    nat: "Ghana",
    club: "Tottenham",
    overall: 81,
  },
{
    name: "Takefusa Kubo",
    pos: "ED",
    nat: "Japan",
    club: "Real Sociedad",
    overall: 81,
  },
{
    name: "Ismaïla Sarr",
    pos: "ED",
    nat: "Senegal",
    club: "Crystal Palace",
    overall: 82,
  },
{
    name: "Brahim Díaz",
    pos: "ED",
    nat: "Morocco",
    club: "Real Madrid",
    overall: 81,
  },
{
    name: "Nicolas Pépé",
    pos: "ED",
    nat: "Ivory Coast",
    club: "Villarreal",
    overall: 81,
  },
{
    name: "Matteo Politano",
    pos: "ED",
    nat: "Italy",
    club: "Napoli",
    overall: 81,
  },
{
    name: "Iñaki Williams",
    pos: "ED",
    nat: "Ghana",
    club: "Athletic Club",
    overall: 81,
  },
{
    name: "Florian Thauvin",
    pos: "ED",
    nat: "France",
    club: "RC Lens",
    overall: 81,
  },
{
    name: "Marc Pubill",
    pos: "DFC",
    nat: "Spain",
    club: "Atletico de Madrid",
    overall: 80,
  },
{
    name: "Federico Chiesa",
    pos: "ED",
    nat: "Italy",
    club: "Liverpool",
    overall: 80,
  },
{
    name: "Donyell Malen",
    pos: "DC",
    nat: "Netherlands",
    club: "Roma",
    overall: 80,
  },
{
    name: "Isi Palazón",
    pos: "MCO",
    nat: "Spain",
    club: "Rayo Vallecano",
    overall: 80,
  },
{
    name: "James Rodriguez",
    pos: "MCO",
    nat: "Colombia",
    club: "Free Agent",
    overall: 80,
  },
{
    name: "Marco Asensio",
    pos: "MCO",
    nat: "Spain",
    club: "Fenerbahçe",
    overall: 80,
  },
{
    name: "João Pedro",
    pos: "DC",
    nat: "Brazil",
    club: "Chelsea",
    overall: 82,
  },
{
    name: "Deniz Undav",
    pos: "DC",
    nat: "Germany",
    club: "Stuttgart",
    overall: 82,
  },
{
    name: "Loïs Openda",
    pos: "DC",
    nat: "Belgium",
    club: "Juventus",
    overall: 82,
  },
{
    name: "Jean-Philippe Mateta",
    pos: "DC",
    nat: "France",
    club: "Crystal Palace",
    overall: 82,
  },
{
    name: "Thomas Müller",
    pos: "MCO",
    nat: "Germany",
    club: "Vancouver Whitecaps",
    overall: 80,
  },
{
    name: "Casemiro",
    pos: "MCD",
    nat: "Brazil",
    club: "Manchester United",
    overall: 82,
  },
{
    name: "Harry Maguire",
    pos: "DFC",
    nat: "England",
    club: "Manchester United",
    overall: 80,
  },
{
    name: "Jadon Sancho",
    pos: "EI",
    nat: "England",
    club: "Manchester United",
    overall: 80,
  },
{
    name: "Noussair Mazraoui",
    pos: "LD",
    nat: "Morocco",
    club: "Manchester United",
    overall: 80,
  },
{
    name: "Benjamin Šeško",
    pos: "DC",
    nat: "Slovenia",
    club: "Manchester United",
    overall: 80,
  },
{
    name: "André Onana",
    pos: "POR",
    nat: "Cameroon",
    club: "Manchester United",
    overall: 80,
  },
{
    name: "Andy Robertson",
    pos: "LI",
    nat: "Scotland",
    club: "Liverpool",
    overall: 82,
  },
{
    name: "Milos Kerkez",
    pos: "LI",
    nat: "Hungary",
    club: "Liverpool",
    overall: 82,
  },
{
    name: "Federico Chiesa",
    pos: "ED",
    nat: "Italy",
    club: "Liverpool",
    overall: 81,
  },
{
    name: "Carlos Augusto",
    pos: "LI",
    nat: "Brazil",
    club: "Inter Milan",
    overall: 81,
  },
{
    name: "Matteo Darmian",
    pos: "LD",
    nat: "Italy",
    club: "Inter Milan",
    overall: 81,
  },
{
    name: "Davide Frattesi",
    pos: "MC",
    nat: "Italy",
    club: "Inter Milan",
    overall: 81,
  },
{
    name: "Youssouf Fofana",
    pos: "MCD",
    nat: "France",
    club: "AC Milan",
    overall: 81,
  },
{
    name: "Kai Havertz",
    pos: "DC",
    nat: "Germany",
    club: "Arsenal",
    overall: 82,
  },
{
    name: "Xavi Simons",
    pos: "MCO",
    nat: "Netherlands",
    club: "Tottenham",
    overall: 82,
  },
{
    name: "Pape Matar Sarr",
    pos: "MCD",
    nat: "Senegal",
    club: "Tottenham",
    overall: 80,
  },
{
    name: "Micky van de Ven",
    pos: "DFC",
    nat: "Netherlands",
    club: "Tottenham",
    overall: 82,
  },
{
    name: "Jeremie Frimpong",
    pos: "LD",
    nat: "Netherlands",
    club: "Liverpool",
    overall: 82,
  },
{
    name: "Fikayo Tomori",
    pos: "DFC",
    nat: "England",
    club: "AC Milan",
    overall: 81,
  },
{
    name: "Kenan Yıldız",
    pos: "MCO",
    nat: "Turkey",
    club: "Juventus",
    overall: 82,
  },
{
    name: "Charles De Ketelaere",
    pos: "MCO",
    nat: "Belgium",
    club: "Atalanta",
    overall: 82,
  },
{
    name: "Oihan Sancet",
    pos: "MCO",
    nat: "Spain",
    club: "Athletic Club",
    overall: 82,
  },
{
    name: "Orkun Kökçü",
    pos: "MC",
    nat: "Turkey",
    club: "Besiktas",
    overall: 82,
  },
{
    name: "Matteo Guendouzi",
    pos: "MC",
    nat: "France",
    club: "Fenerbahçe",
    overall: 82,
  },
{
    name: "Corentin Tolisso",
    pos: "MC",
    nat: "France",
    club: "Olympique Lyonnais",
    overall: 82,
  },
{
    name: "Rafa Silva",
    pos: "MCO",
    nat: "Portugal",
    club: "Benfica",
    overall: 82,
  },
{
    name: "Mateo Kovačić",
    pos: "MC",
    nat: "Croatia",
    club: "Manchester City",
    overall: 82,
  },
{
    name: "Konstantinos Fortounis",
    pos: "MCO",
    nat: "Greece",
    club: "Al Khaleej",
    overall: 82,
  },
{
    name: "Joey Veerman",
    pos: "MC",
    nat: "Netherlands",
    club: "PSV",
    overall: 81,
  },
{
    name: "Moleiro",
    pos: "EI",
    nat: "Spain",
    club: "Villarreal",
    overall: 82,
  },
{
    name: "Iliman Ndiaye",
    pos: "EI",
    nat: "Senegal",
    club: "Everton",
    overall: 82,
  },
{
    name: "Álex Baena",
    pos: "EI",
    nat: "Spain",
    club: "Atletico de Madrid",
    overall: 82,
  }
];
