export const SQUAD_POOL_3 = [
{
    name: "Giuliano Simeone",
    pos: "ED",
    nat: "Argentina",
    club: "Atletico de Madrid",
    overall: 82,
  },
{
    name: "Karim Adeyemi",
    pos: "ED",
    nat: "Germany",
    club: "Borussia Dortmund",
    overall: 82,
  },
{
    name: "Anthony Gordon",
    pos: "EI",
    nat: "England",
    club: "Newcastle United",
    overall: 82,
  },
{
    name: "Pedro Neto",
    pos: "ED",
    nat: "Portugal",
    club: "Chelsea",
    overall: 82,
  },
{
    name: "Marcus Rashford",
    pos: "EI",
    nat: "England",
    club: "Barcelona",
    overall: 82,
  },
{
    name: "Kinglsey Coman",
    pos: "ED",
    nat: "France",
    club: "Al Nassr",
    overall: 82,
  },
{
    name: "Savinho",
    pos: "ED",
    nat: "Brazil",
    club: "Manchester City",
    overall: 81,
  },
{
    name: "Jack Grealish",
    pos: "EI",
    nat: "England",
    club: "Everton",
    overall: 82,
  },
{
    name: "Mitoma",
    pos: "EI",
    nat: "Japan",
    club: "Brighton",
    overall: 81,
  },
{
    name: "David Neres",
    pos: "EI",
    nat: "Brazil",
    club: "Napoli",
    overall: 81,
  },
{
    name: "Leroy Sané",
    pos: "ED",
    nat: "Germany",
    club: "Galatasaray",
    overall: 81,
  },
{
    name: "Álvaro García",
    pos: "EI",
    nat: "Spain",
    club: "Rayo Vallecano",
    overall: 81,
  },
{
    name: "Yannick Carrasco",
    pos: "EI",
    nat: "Belgium",
    club: "Al Shabab",
    overall: 81,
  },
{
    name: "Yan Diomandé",
    pos: "ED",
    nat: "Ivory Coast",
    club: "RB Leipzig",
    overall: 81,
  },
{
    name: "Abde",
    pos: "EI",
    nat: "Morocco",
    club: "Real Betis",
    overall: 80,
  },
{
    name: "Malcom",
    pos: "ED",
    nat: "Brazil",
    club: "Al Hilal",
    overall: 82,
  },
{
    name: "Domenico Berardi",
    pos: "ED",
    nat: "Italy",
    club: "Sassuolo",
    overall: 82,
  },
{
    name: "Iago Aspas",
    pos: "ED",
    nat: "Spain",
    club: "Celta",
    overall: 82,
  },
{
    name: "Memphis Depay",
    pos: "DC",
    nat: "Netherlands",
    club: "Free Agent",
    overall: 80,
  },
{
    name: "Eduardo Camavinga",
    pos: "MC",
    nat: "France",
    club: "Real Madrid",
    overall: 81,
  },
{
    name: "Khéphren Thuram",
    pos: "MC",
    nat: "France",
    club: "Juventus",
    overall: 81,
  },
{
    name: "João Félix",
    pos: "MCO",
    nat: "Portugal",
    club: "Al Nassr",
    overall: 81,
  },
{ name: "Luis Milla", pos: "MC", nat: "Spain", club: "Getafe", overall: 81 },
{
    name: "Christoph Baumgartner",
    pos: "MCO",
    nat: "Austria",
    club: "RB Leipzig",
    overall: 81,
  },
{
    name: "Morgan Gibbs-White",
    pos: "MCO",
    nat: "England",
    club: "Nottingham Forest",
    overall: 81,
  },
{
    name: "Christopher Nkunku",
    pos: "MCO",
    nat: "France",
    club: "AC Milan",
    overall: 81,
  },
{
    name: "Pablo Fornals",
    pos: "MC",
    nat: "Spain",
    club: "Real Betis",
    overall: 81,
  },
{
    name: "Giovani Lo Celso",
    pos: "MCO",
    nat: "Argentina",
    club: "Real Betis",
    overall: 81,
  },
{
    name: "Joelinton",
    pos: "MC",
    nat: "Brazil",
    club: "Newcastle United",
    overall: 81,
  },
{
    name: "Andrej Kramarić",
    pos: "MCO",
    nat: "Croatia",
    club: "Hoffenheim",
    overall: 81,
  },
{
    name: "Ricardo Horta",
    pos: "MCO",
    nat: "Portugal",
    club: "Sporting Clube de Braga",
    overall: 81,
  },
{
    name: "Anderson Talisca",
    pos: "MCO",
    nat: "Brazil",
    club: "Fenerbahçe",
    overall: 81,
  },
{
    name: "Otávio",
    pos: "MC",
    nat: "Portugal",
    club: "Al Qadsiah",
    overall: 81,
  },
{
    name: "Marten de Roon",
    pos: "MC",
    nat: "Netherlands",
    club: "Atalanta",
    overall: 81,
  },
{
    name: "Bryan Cristante",
    pos: "MC",
    nat: "Italy",
    club: "Roma",
    overall: 81,
  },
{
    name: "Leandro Paredes",
    pos: "MC",
    nat: "Argentina",
    club: "Boca Juniors",
    overall: 81,
  },
{
    name: "Hans Vanaken",
    pos: "MCO",
    nat: "Belgium",
    club: "Club Brugge",
    overall: 81,
  },
{
    name: "Koke",
    pos: "MC",
    nat: "Spain",
    club: "Atletico de Madrid",
    overall: 81,
  },
{
    name: "Mikel Jauregizar",
    pos: "MC",
    nat: "Spain",
    club: "Athletic Club",
    overall: 81,
  },
{
    name: "Andrey Santos",
    pos: "MC",
    nat: "Brazil",
    club: "Chelsea",
    overall: 81,
  },
{
    name: "Gabriel Sara",
    pos: "MC",
    nat: "Brazil",
    club: "Galatasaray",
    overall: 80,
  },
{
    name: "Maghnes Akliouche",
    pos: "MCO",
    nat: "France",
    club: "AS Monaco",
    overall: 80,
  },
{
    name: "Ismael Saibari",
    pos: "MCO",
    nat: "Morocco",
    club: "PSV",
    overall: 80,
  },
{
    name: "Piotr Zieliński",
    pos: "MCO",
    nat: "Poland",
    club: "Inter Milan",
    overall: 80,
  },
{
    name: "Pau Torres",
    pos: "DFC",
    nat: "Spain",
    club: "Aston Villa",
    overall: 81,
  },
{
    name: "Marc Guéhi",
    pos: "DFC",
    nat: "England",
    club: "Crystal Palace",
    overall: 82,
  },
{
    name: "Palhinha",
    pos: "MCD",
    nat: "Portugal",
    club: "Tottenham",
    overall: 82,
  },
{
    name: "Lucas Torreira",
    pos: "MCD",
    nat: "Uruguay",
    club: "Galatasaray",
    overall: 82,
  },
{
    name: "Fabinho",
    pos: "MCD",
    nat: "Brazil",
    club: "Al Ittihad",
    overall: 82,
  },
{
    name: "Remo Freuler",
    pos: "MCD",
    nat: "Switzerland",
    club: "Bologna",
    overall: 82,
  },
{
    name: "Serge Gnabry",
    pos: "MCO",
    nat: "Germany",
    club: "Bayern Munich",
    overall: 83,
  },
{
    name: "Adam Wharton",
    pos: "MCD",
    nat: "England",
    club: "Crystal Palace",
    overall: 81,
  },
{
    name: "Amadou Onana",
    pos: "MCD",
    nat: "Belgium",
    club: "Aston Villa",
    overall: 81,
  },
{
    name: "Nico González",
    pos: "MCD",
    nat: "Spain",
    club: "Manchester City",
    overall: 81,
  },
{
    name: "Pedro Porro",
    pos: "LD",
    nat: "Spain",
    club: "Tottenham",
    overall: 82,
  },
{
    name: "Cristian Romero",
    pos: "DFC",
    nat: "Argentina",
    club: "Tottenham",
    overall: 82,
  },
{
    name: "Yassine Bounou",
    pos: "POR",
    nat: "Morocco",
    club: "Al Hilal",
    overall: 82,
  },
{
    name: "Alessio Romagnoli",
    pos: "DFC",
    nat: "Italy",
    club: "Lazio",
    overall: 82,
  },
{
    name: "Fabian Schär",
    pos: "DFC",
    nat: "Switzerland",
    club: "Newcastle United",
    overall: 82,
  },
{
    name: "Nathan Aké",
    pos: "DFC",
    nat: "Netherlands",
    club: "Manchester City",
    overall: 82,
  },
{
    name: "Emre Can",
    pos: "DFC",
    nat: "Germany",
    club: "Borussia Dortmund",
    overall: 82,
  },
{
    name: "John Stones",
    pos: "DFC",
    nat: "England",
    club: "Manchester City",
    overall: 82,
  },
{
    name: "Kalidou Koulibaly",
    pos: "DFC",
    nat: "Senegal",
    club: "Al Hilal",
    overall: 82,
  },
{
    name: "Thiago Silva",
    pos: "DFC",
    nat: "Brazil",
    club: "Porto",
    overall: 82,
  },
{
    name: "Mario Gila",
    pos: "DFC",
    nat: "Spain",
    club: "Lazio",
    overall: 81,
  },
{
    name: "Castello Lukeba",
    pos: "DFC",
    nat: "France",
    club: "RB Leipzig",
    overall: 81,
  },
{
    name: "Aymeric Laporte",
    pos: "DFC",
    nat: "Spain",
    club: "Athletic Club",
    overall: 82,
  },
{
    name: "Robin Le Normand",
    pos: "DFC",
    nat: "Spain",
    club: "Atletico de Madrid",
    overall: 81,
  },
{
    name: "Dean Huijsen",
    pos: "DFC",
    nat: "Spain",
    club: "Real Madrid",
    overall: 81,
  }
];
